#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
extern process_package__taste_protected_object guard_1_protected;
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_get_data_vt_local_destinations[1] = {vt_guard_1_get_data_global_inport_artificial_get_data};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_check_vt_local_destinations[1] = {vt_guard_1_check_global_inport_artificial_check};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_woffsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_offsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_used_size[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_empties[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_first[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_out_msg_recent[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_out_msg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_out_msg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_out_msg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_n_dest[__po_hi_vt_gui_out_msg_nb_ports] = {0,1,1};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_fifo_size[__po_hi_vt_gui_out_msg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_out_msg_destinations[__po_hi_vt_gui_out_msg_nb_ports] = {NULL,__po_hi_vt_gui_out_msg_outport_get_data_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_check_vt_local_destinations};

/*!
 * \fn void vt_gui_out_msg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_out_msg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_out_msg_deliver) stores the incoming request for the 
 * taskvt_gui_out_msg
 */
void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_out_msg_job (void)
 * \brief Function executed by the task vt_gui_out_msg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_out_msg*/
extern void po_hi_c_vt_gui_out_msg_artificial_out_msg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_out_msg);
void* vt_gui_out_msg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_out_msg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_out_msg_k, __po_hi_vt_gui_out_msg_nb_ports, __po_hi_vt_gui_out_msg_queue, __po_hi_vt_gui_out_msg_fifo_size, __po_hi_vt_gui_out_msg_first, __po_hi_vt_gui_out_msg_offsets, __po_hi_vt_gui_out_msg_woffsets, __po_hi_vt_gui_out_msg_n_dest, __po_hi_vt_gui_out_msg_destinations, __po_hi_vt_gui_out_msg_used_size, __po_hi_vt_gui_out_msg_history, __po_hi_vt_gui_out_msg_recent, __po_hi_vt_gui_out_msg_empties, __po_hi_vt_gui_out_msg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_out_msg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_out_msg_local_inport_artificial_out_msg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, &(inport_artificial_out_msg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg);

        }

        po_hi_c_vt_gui_out_msg_artificial_out_msg (chip_vt_gui_out_msg_k, inport_artificial_out_msg_request.vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_get_data_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_check_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_out_msg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_get_data_vt_local_destinations[1] = {vt_guard_1_get_data_global_inport_artificial_get_data};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_check_vt_local_destinations[1] = {vt_guard_1_check_global_inport_artificial_check};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1,1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_get_data_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_check_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_get_data_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_check_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}

__po_hi_port_t __po_hi_vt_guard_1_get_data_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_woffsets[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_offsets[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_used_size[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_empties[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_first[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_request_t __po_hi_vt_guard_1_get_data_recent[__po_hi_vt_guard_1_get_data_nb_ports];
__po_hi_port_t __po_hi_vt_guard_1_get_data_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_guard_1_get_data_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_guard_1_get_data_history[1];
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_n_dest[__po_hi_vt_guard_1_get_data_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_guard_1_get_data_fifo_size[__po_hi_vt_guard_1_get_data_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_guard_1_get_data_destinations[__po_hi_vt_guard_1_get_data_nb_ports] = {NULL,__po_hi_vt_guard_1_get_data_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_guard_1_get_data_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_guard_1_get_data
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_guard_1_get_data_deliver) stores the incoming request for the 
 * taskvt_guard_1_get_data
 */
void vt_guard_1_get_data_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_guard_1_get_data_global_inport_artificial_get_data:
    {
      __po_hi_gqueue_store_in (chip_vt_guard_1_get_data_k, vt_guard_1_get_data_local_inport_artificial_get_data, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_guard_1_get_data_job (void)
 * \brief Function executed by the task vt_guard_1_get_data
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_guard_1_get_data*/
extern void po_hi_c_vt_guard_1_get_data_artificial_get_data 
    (__po_hi_task_id self,
    dataview__myreal_buffer_impl inport_artificial_get_data);
void* vt_guard_1_get_data_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_get_data_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_guard_1_get_data_k, __po_hi_vt_guard_1_get_data_nb_ports, __po_hi_vt_guard_1_get_data_queue, __po_hi_vt_guard_1_get_data_fifo_size, __po_hi_vt_guard_1_get_data_first, __po_hi_vt_guard_1_get_data_offsets, __po_hi_vt_guard_1_get_data_woffsets, __po_hi_vt_guard_1_get_data_n_dest, __po_hi_vt_guard_1_get_data_destinations, __po_hi_vt_guard_1_get_data_used_size, __po_hi_vt_guard_1_get_data_history, __po_hi_vt_guard_1_get_data_recent, __po_hi_vt_guard_1_get_data_empties, __po_hi_vt_guard_1_get_data_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_guard_1_get_data_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_guard_1_get_data_k, &(port));
    __po_hi_compute_next_period (chip_vt_guard_1_get_data_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_guard_1_get_data_local_inport_artificial_get_data:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_guard_1_get_data_k, vt_guard_1_get_data_local_inport_artificial_get_data))
        {
                  __po_hi_gqueue_get_value (chip_vt_guard_1_get_data_k, vt_guard_1_get_data_local_inport_artificial_get_data, &(inport_artificial_get_data_request));
          __po_hi_gqueue_next_value (chip_vt_guard_1_get_data_k, vt_guard_1_get_data_local_inport_artificial_get_data);

        }

        po_hi_c_vt_guard_1_get_data_artificial_get_data (chip_vt_guard_1_get_data_k, inport_artificial_get_data_request.vars.vt_guard_1_get_data_global_inport_artificial_get_data.vt_guard_1_get_data_global_inport_artificial_get_data);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_guard_1_get_data_k, vt_guard_1_get_data_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_guard_1_get_data_k);
  }
}

__po_hi_port_t __po_hi_vt_guard_1_check_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_guard_1_check_woffsets[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_check_offsets[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_check_used_size[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_check_empties[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_port_id_t __po_hi_vt_guard_1_check_first[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_request_t __po_hi_vt_guard_1_check_recent[__po_hi_vt_guard_1_check_nb_ports];
__po_hi_port_t __po_hi_vt_guard_1_check_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_guard_1_check_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_guard_1_check_history[1];
__po_hi_port_id_t __po_hi_vt_guard_1_check_n_dest[__po_hi_vt_guard_1_check_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_guard_1_check_fifo_size[__po_hi_vt_guard_1_check_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_guard_1_check_destinations[__po_hi_vt_guard_1_check_nb_ports] = {NULL,__po_hi_vt_guard_1_check_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_guard_1_check_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_guard_1_check
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_guard_1_check_deliver) stores the incoming request for the 
 * taskvt_guard_1_check
 */
void vt_guard_1_check_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_guard_1_check_global_inport_artificial_check:
    {
      __po_hi_gqueue_store_in (chip_vt_guard_1_check_k, vt_guard_1_check_local_inport_artificial_check, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_guard_1_check_job (void)
 * \brief Function executed by the task vt_guard_1_check
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_guard_1_check*/
extern void po_hi_c_vt_guard_1_check_artificial_check 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_check);
void* vt_guard_1_check_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_check_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_guard_1_check_k, __po_hi_vt_guard_1_check_nb_ports, __po_hi_vt_guard_1_check_queue, __po_hi_vt_guard_1_check_fifo_size, __po_hi_vt_guard_1_check_first, __po_hi_vt_guard_1_check_offsets, __po_hi_vt_guard_1_check_woffsets, __po_hi_vt_guard_1_check_n_dest, __po_hi_vt_guard_1_check_destinations, __po_hi_vt_guard_1_check_used_size, __po_hi_vt_guard_1_check_history, __po_hi_vt_guard_1_check_recent, __po_hi_vt_guard_1_check_empties, __po_hi_vt_guard_1_check_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_guard_1_check_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_guard_1_check_k, &(port));
    __po_hi_compute_next_period (chip_vt_guard_1_check_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_guard_1_check_local_inport_artificial_check:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_guard_1_check_k, vt_guard_1_check_local_inport_artificial_check))
        {
                  __po_hi_gqueue_get_value (chip_vt_guard_1_check_k, vt_guard_1_check_local_inport_artificial_check, &(inport_artificial_check_request));
          __po_hi_gqueue_next_value (chip_vt_guard_1_check_k, vt_guard_1_check_local_inport_artificial_check);

        }

        po_hi_c_vt_guard_1_check_artificial_check (chip_vt_guard_1_check_k, inport_artificial_check_request.vars.vt_guard_1_check_global_inport_artificial_check.vt_guard_1_check_global_inport_artificial_check);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_guard_1_check_k, vt_guard_1_check_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_guard_1_check_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_vt_gui_out_msg_k_entity:
    {
      vt_gui_out_msg_deliver (request);

      break;
    }
    case chip_vt_guard_1_get_data_k_entity:
    {
      vt_guard_1_get_data_deliver (request);

      break;
    }
    case chip_vt_guard_1_check_k_entity:
    {
      vt_guard_1_check_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


