#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE chip_k

#define __po_hi_vt_gui_out_msg_nb_ports 3

#define __po_hi_vt_gui_gui_polling_gui_nb_ports 2

#define __po_hi_vt_guard_1_get_data_nb_ports 2

#define __po_hi_vt_guard_1_check_nb_ports 2

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  chip_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  chip_vt_gui_out_msg_k_entity = 0,
  chip_vt_gui_gui_polling_gui_k_entity = 1,
  chip_vt_guard_1_get_data_k_entity = 2,
  chip_vt_guard_1_check_k_entity = 3,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  chip_vt_gui_out_msg_k = 0,
  chip_vt_gui_gui_polling_gui_k = 1,
  chip_vt_guard_1_get_data_k = 2,
  chip_vt_guard_1_check_k = 3,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 4

#define __PO_HI_TASKS_STACK 200000

#define __PO_HI_NB_PROTECTED 2

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 4

#define __PO_HI_NB_PORTS 9

typedef enum
{
  vt_gui_out_msg_global_inport_artificial_out_msg = 0,
  vt_gui_out_msg_global_outport_get_data_vt = 1,
  vt_gui_out_msg_global_outport_check_vt = 2,
  vt_gui_gui_polling_gui_global_outport_get_data_vt = 3,
  vt_gui_gui_polling_gui_global_outport_check_vt = 4,
  vt_guard_1_get_data_global_inport_artificial_get_data = 5,
  vt_guard_1_get_data_global_outport_out_msg_vt = 6,
  vt_guard_1_check_global_inport_artificial_check = 7,
  vt_guard_1_check_global_outport_out_msg_vt = 8,
  invalid_port_t = -1,
  constant_out_identifier = 10
} __po_hi_port_t;

typedef enum
{
  vt_gui_out_msg_local_inport_artificial_out_msg = 0,
  vt_gui_out_msg_local_outport_get_data_vt = 1,
  vt_gui_out_msg_local_outport_check_vt = 2,
  vt_gui_gui_polling_gui_local_outport_get_data_vt = 0,
  vt_gui_gui_polling_gui_local_outport_check_vt = 1,
  vt_guard_1_get_data_local_inport_artificial_get_data = 0,
  vt_guard_1_get_data_local_outport_out_msg_vt = 1,
  vt_guard_1_check_local_inport_artificial_check = 0,
  vt_guard_1_check_local_outport_out_msg_vt = 1,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 0

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_vt_gui_out_msg_nb_ports, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_guard_1_get_data_nb_ports, __po_hi_vt_guard_1_check_nb_ports

#endif
