#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_gui_transaction_deliver 
    (__po_hi_request_t* request);

void* vt_gui_transaction_job (void);

void vt_gui_display_deliver 
    (__po_hi_request_t* request);

void* vt_gui_display_job (void);

void vt_gui_eject_card_deliver 
    (__po_hi_request_t* request);

void* vt_gui_eject_card_job (void);

void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request);

void* vt_gui_out_msg_job (void);

void vt_gui_gui_polling_gui_deliver 
    (__po_hi_request_t* request);

void* vt_gui_gui_polling_gui_job (void);

void vt_atm_accept_card_deliver 
    (__po_hi_request_t* request);

void* vt_atm_accept_card_job (void);

void vt_atm_reject_transaction_deliver 
    (__po_hi_request_t* request);

void* vt_atm_reject_transaction_job (void);

void vt_atm_out_of_service_deliver 
    (__po_hi_request_t* request);

void* vt_atm_out_of_service_job (void);

void vt_atm_abort_out_deliver 
    (__po_hi_request_t* request);

void* vt_atm_abort_out_job (void);

void vt_atm_amount_deliver 
    (__po_hi_request_t* request);

void* vt_atm_amount_job (void);

void vt_atm_other_amount_deliver 
    (__po_hi_request_t* request);

void* vt_atm_other_amount_job (void);

void vt_atm_digit_deliver 
    (__po_hi_request_t* request);

void* vt_atm_digit_job (void);

void vt_atm_ok_deliver 
    (__po_hi_request_t* request);

void* vt_atm_ok_job (void);

void vt_atm_transaction_succeseeded_deliver 
    (__po_hi_request_t* request);

void* vt_atm_transaction_succeseeded_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
