#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
extern process_package__taste_protected_object atm_protected;
__po_hi_port_t __po_hi_vt_gui_transaction_outport_accept_card_vt_local_destinations[1] = {vt_atm_accept_card_global_inport_artificial_accept_card};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_reject_transaction_vt_local_destinations[1] = {vt_atm_reject_transaction_global_inport_artificial_reject_transaction};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_out_of_service_vt_local_destinations[1] = {vt_atm_out_of_service_global_inport_artificial_out_of_service};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_abort_out_vt_local_destinations[1] = {vt_atm_abort_out_global_inport_artificial_abort_out};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_amount_vt_local_destinations[1] = {vt_atm_amount_global_inport_artificial_amount};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_other_amount_vt_local_destinations[1] = {vt_atm_other_amount_global_inport_artificial_other_amount};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_digit_vt_local_destinations[1] = {vt_atm_digit_global_inport_artificial_digit};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_ok_vt_local_destinations[1] = {vt_atm_ok_global_inport_artificial_ok};
__po_hi_port_t __po_hi_vt_gui_transaction_outport_transaction_succeseeded_vt_local_destinations[1] = {vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded};
__po_hi_port_id_t __po_hi_vt_gui_transaction_woffsets[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_transaction_offsets[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_transaction_used_size[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_transaction_empties[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_transaction_first[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_request_t __po_hi_vt_gui_transaction_recent[__po_hi_vt_gui_transaction_nb_ports];
__po_hi_port_t __po_hi_vt_gui_transaction_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_transaction_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_transaction_history[1];
__po_hi_port_id_t __po_hi_vt_gui_transaction_n_dest[__po_hi_vt_gui_transaction_nb_ports] = {0,1,1,1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_transaction_fifo_size[__po_hi_vt_gui_transaction_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_transaction_destinations[__po_hi_vt_gui_transaction_nb_ports] = {NULL,__po_hi_vt_gui_transaction_outport_accept_card_vt_local_destinations,__po_hi_vt_gui_transaction_outport_reject_transaction_vt_local_destinations,__po_hi_vt_gui_transaction_outport_out_of_service_vt_local_destinations,__po_hi_vt_gui_transaction_outport_abort_out_vt_local_destinations,__po_hi_vt_gui_transaction_outport_amount_vt_local_destinations,__po_hi_vt_gui_transaction_outport_other_amount_vt_local_destinations,__po_hi_vt_gui_transaction_outport_digit_vt_local_destinations,__po_hi_vt_gui_transaction_outport_ok_vt_local_destinations,__po_hi_vt_gui_transaction_outport_transaction_succeseeded_vt_local_destinations};

/*!
 * \fn void vt_gui_transaction_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_transaction
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_transaction_deliver) stores the incoming request for the 
 * taskvt_gui_transaction
 */
void vt_gui_transaction_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_transaction_global_inport_artificial_transaction:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_transaction_k, vt_gui_transaction_local_inport_artificial_transaction, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_transaction_job (void)
 * \brief Function executed by the task vt_gui_transaction
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_transaction*/
extern void po_hi_c_vt_gui_transaction_artificial_transaction 
    (__po_hi_task_id self,
    dataview__amount_buffer_impl inport_artificial_transaction);
void* vt_gui_transaction_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_transaction_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_transaction_k, __po_hi_vt_gui_transaction_nb_ports, __po_hi_vt_gui_transaction_queue, __po_hi_vt_gui_transaction_fifo_size, __po_hi_vt_gui_transaction_first, __po_hi_vt_gui_transaction_offsets, __po_hi_vt_gui_transaction_woffsets, __po_hi_vt_gui_transaction_n_dest, __po_hi_vt_gui_transaction_destinations, __po_hi_vt_gui_transaction_used_size, __po_hi_vt_gui_transaction_history, __po_hi_vt_gui_transaction_recent, __po_hi_vt_gui_transaction_empties, __po_hi_vt_gui_transaction_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_transaction_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_transaction_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_transaction_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_transaction_local_inport_artificial_transaction:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_transaction_k, vt_gui_transaction_local_inport_artificial_transaction))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_transaction_k, vt_gui_transaction_local_inport_artificial_transaction, &(inport_artificial_transaction_request));
          __po_hi_gqueue_next_value (chip_vt_gui_transaction_k, vt_gui_transaction_local_inport_artificial_transaction);

        }

        po_hi_c_vt_gui_transaction_artificial_transaction (chip_vt_gui_transaction_k, inport_artificial_transaction_request.vars.vt_gui_transaction_global_inport_artificial_transaction.vt_gui_transaction_global_inport_artificial_transaction);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_accept_card_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_reject_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_out_of_service_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_abort_out_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_other_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_digit_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_ok_vt);
    error =
     __po_hi_send_output (chip_vt_gui_transaction_k, vt_gui_transaction_global_outport_transaction_succeseeded_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_transaction_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_display_outport_accept_card_vt_local_destinations[1] = {vt_atm_accept_card_global_inport_artificial_accept_card};
__po_hi_port_t __po_hi_vt_gui_display_outport_reject_transaction_vt_local_destinations[1] = {vt_atm_reject_transaction_global_inport_artificial_reject_transaction};
__po_hi_port_t __po_hi_vt_gui_display_outport_out_of_service_vt_local_destinations[1] = {vt_atm_out_of_service_global_inport_artificial_out_of_service};
__po_hi_port_t __po_hi_vt_gui_display_outport_abort_out_vt_local_destinations[1] = {vt_atm_abort_out_global_inport_artificial_abort_out};
__po_hi_port_t __po_hi_vt_gui_display_outport_amount_vt_local_destinations[1] = {vt_atm_amount_global_inport_artificial_amount};
__po_hi_port_t __po_hi_vt_gui_display_outport_other_amount_vt_local_destinations[1] = {vt_atm_other_amount_global_inport_artificial_other_amount};
__po_hi_port_t __po_hi_vt_gui_display_outport_digit_vt_local_destinations[1] = {vt_atm_digit_global_inport_artificial_digit};
__po_hi_port_t __po_hi_vt_gui_display_outport_ok_vt_local_destinations[1] = {vt_atm_ok_global_inport_artificial_ok};
__po_hi_port_t __po_hi_vt_gui_display_outport_transaction_succeseeded_vt_local_destinations[1] = {vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded};
__po_hi_port_id_t __po_hi_vt_gui_display_woffsets[__po_hi_vt_gui_display_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_display_offsets[__po_hi_vt_gui_display_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_display_used_size[__po_hi_vt_gui_display_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_display_empties[__po_hi_vt_gui_display_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_display_first[__po_hi_vt_gui_display_nb_ports];
__po_hi_request_t __po_hi_vt_gui_display_recent[__po_hi_vt_gui_display_nb_ports];
__po_hi_port_t __po_hi_vt_gui_display_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_display_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_display_history[1];
__po_hi_port_id_t __po_hi_vt_gui_display_n_dest[__po_hi_vt_gui_display_nb_ports] = {0,1,1,1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_display_fifo_size[__po_hi_vt_gui_display_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_display_destinations[__po_hi_vt_gui_display_nb_ports] = {NULL,__po_hi_vt_gui_display_outport_accept_card_vt_local_destinations,__po_hi_vt_gui_display_outport_reject_transaction_vt_local_destinations,__po_hi_vt_gui_display_outport_out_of_service_vt_local_destinations,__po_hi_vt_gui_display_outport_abort_out_vt_local_destinations,__po_hi_vt_gui_display_outport_amount_vt_local_destinations,__po_hi_vt_gui_display_outport_other_amount_vt_local_destinations,__po_hi_vt_gui_display_outport_digit_vt_local_destinations,__po_hi_vt_gui_display_outport_ok_vt_local_destinations,__po_hi_vt_gui_display_outport_transaction_succeseeded_vt_local_destinations};

/*!
 * \fn void vt_gui_display_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_display
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_display_deliver) stores the incoming request for the 
 * taskvt_gui_display
 */
void vt_gui_display_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_display_global_inport_artificial_display:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_display_k, vt_gui_display_local_inport_artificial_display, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_display_job (void)
 * \brief Function executed by the task vt_gui_display
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_display*/
extern void po_hi_c_vt_gui_display_artificial_display 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_display);
void* vt_gui_display_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_display_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_display_k, __po_hi_vt_gui_display_nb_ports, __po_hi_vt_gui_display_queue, __po_hi_vt_gui_display_fifo_size, __po_hi_vt_gui_display_first, __po_hi_vt_gui_display_offsets, __po_hi_vt_gui_display_woffsets, __po_hi_vt_gui_display_n_dest, __po_hi_vt_gui_display_destinations, __po_hi_vt_gui_display_used_size, __po_hi_vt_gui_display_history, __po_hi_vt_gui_display_recent, __po_hi_vt_gui_display_empties, __po_hi_vt_gui_display_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_display_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_display_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_display_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_display_local_inport_artificial_display:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_display_k, vt_gui_display_local_inport_artificial_display))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_display_k, vt_gui_display_local_inport_artificial_display, &(inport_artificial_display_request));
          __po_hi_gqueue_next_value (chip_vt_gui_display_k, vt_gui_display_local_inport_artificial_display);

        }

        po_hi_c_vt_gui_display_artificial_display (chip_vt_gui_display_k, inport_artificial_display_request.vars.vt_gui_display_global_inport_artificial_display.vt_gui_display_global_inport_artificial_display);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_accept_card_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_reject_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_out_of_service_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_abort_out_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_other_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_digit_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_ok_vt);
    error =
     __po_hi_send_output (chip_vt_gui_display_k, vt_gui_display_global_outport_transaction_succeseeded_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_display_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_eject_card_outport_accept_card_vt_local_destinations[1] = {vt_atm_accept_card_global_inport_artificial_accept_card};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_reject_transaction_vt_local_destinations[1] = {vt_atm_reject_transaction_global_inport_artificial_reject_transaction};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_out_of_service_vt_local_destinations[1] = {vt_atm_out_of_service_global_inport_artificial_out_of_service};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_abort_out_vt_local_destinations[1] = {vt_atm_abort_out_global_inport_artificial_abort_out};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_amount_vt_local_destinations[1] = {vt_atm_amount_global_inport_artificial_amount};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_other_amount_vt_local_destinations[1] = {vt_atm_other_amount_global_inport_artificial_other_amount};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_digit_vt_local_destinations[1] = {vt_atm_digit_global_inport_artificial_digit};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_ok_vt_local_destinations[1] = {vt_atm_ok_global_inport_artificial_ok};
__po_hi_port_t __po_hi_vt_gui_eject_card_outport_transaction_succeseeded_vt_local_destinations[1] = {vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded};
__po_hi_port_id_t __po_hi_vt_gui_eject_card_woffsets[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_eject_card_offsets[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_eject_card_used_size[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_eject_card_empties[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_eject_card_first[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_request_t __po_hi_vt_gui_eject_card_recent[__po_hi_vt_gui_eject_card_nb_ports];
__po_hi_port_t __po_hi_vt_gui_eject_card_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_eject_card_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_eject_card_history[1];
__po_hi_port_id_t __po_hi_vt_gui_eject_card_n_dest[__po_hi_vt_gui_eject_card_nb_ports] = {0,1,1,1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_eject_card_fifo_size[__po_hi_vt_gui_eject_card_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_eject_card_destinations[__po_hi_vt_gui_eject_card_nb_ports] = {NULL,__po_hi_vt_gui_eject_card_outport_accept_card_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_reject_transaction_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_out_of_service_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_abort_out_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_amount_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_other_amount_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_digit_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_ok_vt_local_destinations,__po_hi_vt_gui_eject_card_outport_transaction_succeseeded_vt_local_destinations};

/*!
 * \fn void vt_gui_eject_card_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_eject_card
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_eject_card_deliver) stores the incoming request for the 
 * taskvt_gui_eject_card
 */
void vt_gui_eject_card_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_eject_card_global_inport_artificial_eject_card:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_eject_card_k, vt_gui_eject_card_local_inport_artificial_eject_card, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_eject_card_job (void)
 * \brief Function executed by the task vt_gui_eject_card
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_eject_card*/
extern void po_hi_c_vt_gui_eject_card_artificial_eject_card 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_eject_card);
void* vt_gui_eject_card_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_eject_card_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_eject_card_k, __po_hi_vt_gui_eject_card_nb_ports, __po_hi_vt_gui_eject_card_queue, __po_hi_vt_gui_eject_card_fifo_size, __po_hi_vt_gui_eject_card_first, __po_hi_vt_gui_eject_card_offsets, __po_hi_vt_gui_eject_card_woffsets, __po_hi_vt_gui_eject_card_n_dest, __po_hi_vt_gui_eject_card_destinations, __po_hi_vt_gui_eject_card_used_size, __po_hi_vt_gui_eject_card_history, __po_hi_vt_gui_eject_card_recent, __po_hi_vt_gui_eject_card_empties, __po_hi_vt_gui_eject_card_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_eject_card_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_eject_card_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_eject_card_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_eject_card_local_inport_artificial_eject_card:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_eject_card_k, vt_gui_eject_card_local_inport_artificial_eject_card))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_eject_card_k, vt_gui_eject_card_local_inport_artificial_eject_card, &(inport_artificial_eject_card_request));
          __po_hi_gqueue_next_value (chip_vt_gui_eject_card_k, vt_gui_eject_card_local_inport_artificial_eject_card);

        }

        po_hi_c_vt_gui_eject_card_artificial_eject_card (chip_vt_gui_eject_card_k, inport_artificial_eject_card_request.vars.vt_gui_eject_card_global_inport_artificial_eject_card.vt_gui_eject_card_global_inport_artificial_eject_card);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_accept_card_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_reject_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_out_of_service_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_abort_out_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_other_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_digit_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_ok_vt);
    error =
     __po_hi_send_output (chip_vt_gui_eject_card_k, vt_gui_eject_card_global_outport_transaction_succeseeded_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_eject_card_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_out_msg_outport_accept_card_vt_local_destinations[1] = {vt_atm_accept_card_global_inport_artificial_accept_card};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_reject_transaction_vt_local_destinations[1] = {vt_atm_reject_transaction_global_inport_artificial_reject_transaction};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_out_of_service_vt_local_destinations[1] = {vt_atm_out_of_service_global_inport_artificial_out_of_service};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_abort_out_vt_local_destinations[1] = {vt_atm_abort_out_global_inport_artificial_abort_out};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_amount_vt_local_destinations[1] = {vt_atm_amount_global_inport_artificial_amount};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_other_amount_vt_local_destinations[1] = {vt_atm_other_amount_global_inport_artificial_other_amount};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_digit_vt_local_destinations[1] = {vt_atm_digit_global_inport_artificial_digit};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_ok_vt_local_destinations[1] = {vt_atm_ok_global_inport_artificial_ok};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_transaction_succeseeded_vt_local_destinations[1] = {vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_woffsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_offsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_used_size[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_empties[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_first[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_out_msg_recent[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_out_msg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_out_msg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_out_msg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_n_dest[__po_hi_vt_gui_out_msg_nb_ports] = {0,1,1,1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_fifo_size[__po_hi_vt_gui_out_msg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_out_msg_destinations[__po_hi_vt_gui_out_msg_nb_ports] = {NULL,__po_hi_vt_gui_out_msg_outport_accept_card_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_reject_transaction_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_out_of_service_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_abort_out_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_amount_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_other_amount_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_digit_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_ok_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_transaction_succeseeded_vt_local_destinations};

/*!
 * \fn void vt_gui_out_msg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_out_msg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_out_msg_deliver) stores the incoming request for the 
 * taskvt_gui_out_msg
 */
void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_out_msg_job (void)
 * \brief Function executed by the task vt_gui_out_msg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_out_msg*/
extern void po_hi_c_vt_gui_out_msg_artificial_out_msg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_out_msg);
void* vt_gui_out_msg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_out_msg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_out_msg_k, __po_hi_vt_gui_out_msg_nb_ports, __po_hi_vt_gui_out_msg_queue, __po_hi_vt_gui_out_msg_fifo_size, __po_hi_vt_gui_out_msg_first, __po_hi_vt_gui_out_msg_offsets, __po_hi_vt_gui_out_msg_woffsets, __po_hi_vt_gui_out_msg_n_dest, __po_hi_vt_gui_out_msg_destinations, __po_hi_vt_gui_out_msg_used_size, __po_hi_vt_gui_out_msg_history, __po_hi_vt_gui_out_msg_recent, __po_hi_vt_gui_out_msg_empties, __po_hi_vt_gui_out_msg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_out_msg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_out_msg_local_inport_artificial_out_msg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, &(inport_artificial_out_msg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg);

        }

        po_hi_c_vt_gui_out_msg_artificial_out_msg (chip_vt_gui_out_msg_k, inport_artificial_out_msg_request.vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_accept_card_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_reject_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_out_of_service_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_abort_out_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_other_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_digit_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_ok_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_transaction_succeseeded_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_out_msg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_accept_card_vt_local_destinations[1] = {vt_atm_accept_card_global_inport_artificial_accept_card};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_reject_transaction_vt_local_destinations[1] = {vt_atm_reject_transaction_global_inport_artificial_reject_transaction};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_out_of_service_vt_local_destinations[1] = {vt_atm_out_of_service_global_inport_artificial_out_of_service};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_abort_out_vt_local_destinations[1] = {vt_atm_abort_out_global_inport_artificial_abort_out};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_amount_vt_local_destinations[1] = {vt_atm_amount_global_inport_artificial_amount};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_other_amount_vt_local_destinations[1] = {vt_atm_other_amount_global_inport_artificial_other_amount};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_digit_vt_local_destinations[1] = {vt_atm_digit_global_inport_artificial_digit};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_ok_vt_local_destinations[1] = {vt_atm_ok_global_inport_artificial_ok};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_transaction_succeseeded_vt_local_destinations[1] = {vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1,1,1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_accept_card_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_reject_transaction_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_out_of_service_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_abort_out_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_amount_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_other_amount_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_digit_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_ok_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_transaction_succeseeded_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_accept_card_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_reject_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_out_of_service_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_abort_out_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_other_amount_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_digit_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_ok_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_transaction_succeseeded_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_accept_card_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_accept_card_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_accept_card_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_accept_card_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_accept_card_woffsets[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_accept_card_offsets[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_accept_card_used_size[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_accept_card_empties[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_accept_card_first[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_request_t __po_hi_vt_atm_accept_card_recent[__po_hi_vt_atm_accept_card_nb_ports];
__po_hi_port_t __po_hi_vt_atm_accept_card_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_accept_card_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_accept_card_history[1];
__po_hi_port_id_t __po_hi_vt_atm_accept_card_n_dest[__po_hi_vt_atm_accept_card_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_accept_card_fifo_size[__po_hi_vt_atm_accept_card_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_accept_card_destinations[__po_hi_vt_atm_accept_card_nb_ports] = {NULL,__po_hi_vt_atm_accept_card_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_accept_card_outport_transaction_vt_local_destinations,__po_hi_vt_atm_accept_card_outport_display_vt_local_destinations,__po_hi_vt_atm_accept_card_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_accept_card_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_accept_card
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_accept_card_deliver) stores the incoming request for the 
 * taskvt_atm_accept_card
 */
void vt_atm_accept_card_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_accept_card_global_inport_artificial_accept_card:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_accept_card_k, vt_atm_accept_card_local_inport_artificial_accept_card, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_accept_card_job (void)
 * \brief Function executed by the task vt_atm_accept_card
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_accept_card*/
extern void po_hi_c_vt_atm_accept_card_artificial_accept_card 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_accept_card);
void* vt_atm_accept_card_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_accept_card_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_accept_card_k, __po_hi_vt_atm_accept_card_nb_ports, __po_hi_vt_atm_accept_card_queue, __po_hi_vt_atm_accept_card_fifo_size, __po_hi_vt_atm_accept_card_first, __po_hi_vt_atm_accept_card_offsets, __po_hi_vt_atm_accept_card_woffsets, __po_hi_vt_atm_accept_card_n_dest, __po_hi_vt_atm_accept_card_destinations, __po_hi_vt_atm_accept_card_used_size, __po_hi_vt_atm_accept_card_history, __po_hi_vt_atm_accept_card_recent, __po_hi_vt_atm_accept_card_empties, __po_hi_vt_atm_accept_card_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_accept_card_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_accept_card_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_accept_card_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_accept_card_local_inport_artificial_accept_card:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_accept_card_k, vt_atm_accept_card_local_inport_artificial_accept_card))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_accept_card_k, vt_atm_accept_card_local_inport_artificial_accept_card, &(inport_artificial_accept_card_request));
          __po_hi_gqueue_next_value (chip_vt_atm_accept_card_k, vt_atm_accept_card_local_inport_artificial_accept_card);

        }

        po_hi_c_vt_atm_accept_card_artificial_accept_card (chip_vt_atm_accept_card_k, inport_artificial_accept_card_request.vars.vt_atm_accept_card_global_inport_artificial_accept_card.vt_atm_accept_card_global_inport_artificial_accept_card);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_accept_card_k, vt_atm_accept_card_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_accept_card_k, vt_atm_accept_card_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_accept_card_k, vt_atm_accept_card_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_accept_card_k, vt_atm_accept_card_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_accept_card_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_reject_transaction_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_reject_transaction_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_reject_transaction_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_reject_transaction_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_woffsets[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_offsets[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_used_size[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_empties[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_first[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_request_t __po_hi_vt_atm_reject_transaction_recent[__po_hi_vt_atm_reject_transaction_nb_ports];
__po_hi_port_t __po_hi_vt_atm_reject_transaction_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_reject_transaction_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_reject_transaction_history[1];
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_n_dest[__po_hi_vt_atm_reject_transaction_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_reject_transaction_fifo_size[__po_hi_vt_atm_reject_transaction_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_reject_transaction_destinations[__po_hi_vt_atm_reject_transaction_nb_ports] = {NULL,__po_hi_vt_atm_reject_transaction_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_reject_transaction_outport_transaction_vt_local_destinations,__po_hi_vt_atm_reject_transaction_outport_display_vt_local_destinations,__po_hi_vt_atm_reject_transaction_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_reject_transaction_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_reject_transaction
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_reject_transaction_deliver) stores the incoming request for the 
 * taskvt_atm_reject_transaction
 */
void vt_atm_reject_transaction_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_reject_transaction_global_inport_artificial_reject_transaction:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_local_inport_artificial_reject_transaction, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_reject_transaction_job (void)
 * \brief Function executed by the task vt_atm_reject_transaction
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_reject_transaction*/
extern void po_hi_c_vt_atm_reject_transaction_artificial_reject_transaction 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_reject_transaction);
void* vt_atm_reject_transaction_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_reject_transaction_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_reject_transaction_k, __po_hi_vt_atm_reject_transaction_nb_ports, __po_hi_vt_atm_reject_transaction_queue, __po_hi_vt_atm_reject_transaction_fifo_size, __po_hi_vt_atm_reject_transaction_first, __po_hi_vt_atm_reject_transaction_offsets, __po_hi_vt_atm_reject_transaction_woffsets, __po_hi_vt_atm_reject_transaction_n_dest, __po_hi_vt_atm_reject_transaction_destinations, __po_hi_vt_atm_reject_transaction_used_size, __po_hi_vt_atm_reject_transaction_history, __po_hi_vt_atm_reject_transaction_recent, __po_hi_vt_atm_reject_transaction_empties, __po_hi_vt_atm_reject_transaction_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_reject_transaction_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_reject_transaction_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_reject_transaction_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_reject_transaction_local_inport_artificial_reject_transaction:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_local_inport_artificial_reject_transaction))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_local_inport_artificial_reject_transaction, &(inport_artificial_reject_transaction_request));
          __po_hi_gqueue_next_value (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_local_inport_artificial_reject_transaction);

        }

        po_hi_c_vt_atm_reject_transaction_artificial_reject_transaction (chip_vt_atm_reject_transaction_k, inport_artificial_reject_transaction_request.vars.vt_atm_reject_transaction_global_inport_artificial_reject_transaction.vt_atm_reject_transaction_global_inport_artificial_reject_transaction);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_reject_transaction_k, vt_atm_reject_transaction_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_reject_transaction_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_out_of_service_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_out_of_service_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_out_of_service_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_out_of_service_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_woffsets[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_offsets[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_used_size[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_empties[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_first[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_request_t __po_hi_vt_atm_out_of_service_recent[__po_hi_vt_atm_out_of_service_nb_ports];
__po_hi_port_t __po_hi_vt_atm_out_of_service_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_out_of_service_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_out_of_service_history[1];
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_n_dest[__po_hi_vt_atm_out_of_service_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_out_of_service_fifo_size[__po_hi_vt_atm_out_of_service_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_out_of_service_destinations[__po_hi_vt_atm_out_of_service_nb_ports] = {NULL,__po_hi_vt_atm_out_of_service_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_out_of_service_outport_transaction_vt_local_destinations,__po_hi_vt_atm_out_of_service_outport_display_vt_local_destinations,__po_hi_vt_atm_out_of_service_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_out_of_service_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_out_of_service
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_out_of_service_deliver) stores the incoming request for the 
 * taskvt_atm_out_of_service
 */
void vt_atm_out_of_service_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_out_of_service_global_inport_artificial_out_of_service:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_local_inport_artificial_out_of_service, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_out_of_service_job (void)
 * \brief Function executed by the task vt_atm_out_of_service
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_out_of_service*/
extern void po_hi_c_vt_atm_out_of_service_artificial_out_of_service 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_out_of_service);
void* vt_atm_out_of_service_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_out_of_service_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_out_of_service_k, __po_hi_vt_atm_out_of_service_nb_ports, __po_hi_vt_atm_out_of_service_queue, __po_hi_vt_atm_out_of_service_fifo_size, __po_hi_vt_atm_out_of_service_first, __po_hi_vt_atm_out_of_service_offsets, __po_hi_vt_atm_out_of_service_woffsets, __po_hi_vt_atm_out_of_service_n_dest, __po_hi_vt_atm_out_of_service_destinations, __po_hi_vt_atm_out_of_service_used_size, __po_hi_vt_atm_out_of_service_history, __po_hi_vt_atm_out_of_service_recent, __po_hi_vt_atm_out_of_service_empties, __po_hi_vt_atm_out_of_service_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_out_of_service_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_out_of_service_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_out_of_service_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_out_of_service_local_inport_artificial_out_of_service:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_local_inport_artificial_out_of_service))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_local_inport_artificial_out_of_service, &(inport_artificial_out_of_service_request));
          __po_hi_gqueue_next_value (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_local_inport_artificial_out_of_service);

        }

        po_hi_c_vt_atm_out_of_service_artificial_out_of_service (chip_vt_atm_out_of_service_k, inport_artificial_out_of_service_request.vars.vt_atm_out_of_service_global_inport_artificial_out_of_service.vt_atm_out_of_service_global_inport_artificial_out_of_service);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_out_of_service_k, vt_atm_out_of_service_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_out_of_service_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_abort_out_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_abort_out_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_abort_out_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_abort_out_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_abort_out_woffsets[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_abort_out_offsets[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_abort_out_used_size[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_abort_out_empties[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_abort_out_first[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_request_t __po_hi_vt_atm_abort_out_recent[__po_hi_vt_atm_abort_out_nb_ports];
__po_hi_port_t __po_hi_vt_atm_abort_out_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_abort_out_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_abort_out_history[1];
__po_hi_port_id_t __po_hi_vt_atm_abort_out_n_dest[__po_hi_vt_atm_abort_out_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_abort_out_fifo_size[__po_hi_vt_atm_abort_out_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_abort_out_destinations[__po_hi_vt_atm_abort_out_nb_ports] = {NULL,__po_hi_vt_atm_abort_out_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_abort_out_outport_transaction_vt_local_destinations,__po_hi_vt_atm_abort_out_outport_display_vt_local_destinations,__po_hi_vt_atm_abort_out_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_abort_out_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_abort_out
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_abort_out_deliver) stores the incoming request for the 
 * taskvt_atm_abort_out
 */
void vt_atm_abort_out_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_abort_out_global_inport_artificial_abort_out:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_abort_out_k, vt_atm_abort_out_local_inport_artificial_abort_out, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_abort_out_job (void)
 * \brief Function executed by the task vt_atm_abort_out
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_abort_out*/
extern void po_hi_c_vt_atm_abort_out_artificial_abort_out 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_abort_out);
void* vt_atm_abort_out_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_abort_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_abort_out_k, __po_hi_vt_atm_abort_out_nb_ports, __po_hi_vt_atm_abort_out_queue, __po_hi_vt_atm_abort_out_fifo_size, __po_hi_vt_atm_abort_out_first, __po_hi_vt_atm_abort_out_offsets, __po_hi_vt_atm_abort_out_woffsets, __po_hi_vt_atm_abort_out_n_dest, __po_hi_vt_atm_abort_out_destinations, __po_hi_vt_atm_abort_out_used_size, __po_hi_vt_atm_abort_out_history, __po_hi_vt_atm_abort_out_recent, __po_hi_vt_atm_abort_out_empties, __po_hi_vt_atm_abort_out_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_abort_out_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_abort_out_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_abort_out_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_abort_out_local_inport_artificial_abort_out:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_abort_out_k, vt_atm_abort_out_local_inport_artificial_abort_out))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_abort_out_k, vt_atm_abort_out_local_inport_artificial_abort_out, &(inport_artificial_abort_out_request));
          __po_hi_gqueue_next_value (chip_vt_atm_abort_out_k, vt_atm_abort_out_local_inport_artificial_abort_out);

        }

        po_hi_c_vt_atm_abort_out_artificial_abort_out (chip_vt_atm_abort_out_k, inport_artificial_abort_out_request.vars.vt_atm_abort_out_global_inport_artificial_abort_out.vt_atm_abort_out_global_inport_artificial_abort_out);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_abort_out_k, vt_atm_abort_out_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_abort_out_k, vt_atm_abort_out_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_abort_out_k, vt_atm_abort_out_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_abort_out_k, vt_atm_abort_out_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_abort_out_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_amount_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_amount_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_amount_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_amount_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_amount_woffsets[__po_hi_vt_atm_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_amount_offsets[__po_hi_vt_atm_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_amount_used_size[__po_hi_vt_atm_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_amount_empties[__po_hi_vt_atm_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_amount_first[__po_hi_vt_atm_amount_nb_ports];
__po_hi_request_t __po_hi_vt_atm_amount_recent[__po_hi_vt_atm_amount_nb_ports];
__po_hi_port_t __po_hi_vt_atm_amount_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_amount_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_amount_history[1];
__po_hi_port_id_t __po_hi_vt_atm_amount_n_dest[__po_hi_vt_atm_amount_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_amount_fifo_size[__po_hi_vt_atm_amount_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_amount_destinations[__po_hi_vt_atm_amount_nb_ports] = {NULL,__po_hi_vt_atm_amount_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_amount_outport_transaction_vt_local_destinations,__po_hi_vt_atm_amount_outport_display_vt_local_destinations,__po_hi_vt_atm_amount_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_amount_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_amount
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_amount_deliver) stores the incoming request for the 
 * taskvt_atm_amount
 */
void vt_atm_amount_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_amount_global_inport_artificial_amount:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_amount_k, vt_atm_amount_local_inport_artificial_amount, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_amount_job (void)
 * \brief Function executed by the task vt_atm_amount
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_amount*/
extern void po_hi_c_vt_atm_amount_artificial_amount 
    (__po_hi_task_id self,
    dataview__amount_buffer_impl inport_artificial_amount);
void* vt_atm_amount_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_amount_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_amount_k, __po_hi_vt_atm_amount_nb_ports, __po_hi_vt_atm_amount_queue, __po_hi_vt_atm_amount_fifo_size, __po_hi_vt_atm_amount_first, __po_hi_vt_atm_amount_offsets, __po_hi_vt_atm_amount_woffsets, __po_hi_vt_atm_amount_n_dest, __po_hi_vt_atm_amount_destinations, __po_hi_vt_atm_amount_used_size, __po_hi_vt_atm_amount_history, __po_hi_vt_atm_amount_recent, __po_hi_vt_atm_amount_empties, __po_hi_vt_atm_amount_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_amount_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_amount_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_amount_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_amount_local_inport_artificial_amount:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_amount_k, vt_atm_amount_local_inport_artificial_amount))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_amount_k, vt_atm_amount_local_inport_artificial_amount, &(inport_artificial_amount_request));
          __po_hi_gqueue_next_value (chip_vt_atm_amount_k, vt_atm_amount_local_inport_artificial_amount);

        }

        po_hi_c_vt_atm_amount_artificial_amount (chip_vt_atm_amount_k, inport_artificial_amount_request.vars.vt_atm_amount_global_inport_artificial_amount.vt_atm_amount_global_inport_artificial_amount);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_amount_k, vt_atm_amount_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_amount_k, vt_atm_amount_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_amount_k, vt_atm_amount_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_amount_k, vt_atm_amount_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_amount_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_other_amount_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_other_amount_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_other_amount_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_other_amount_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_other_amount_woffsets[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_other_amount_offsets[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_other_amount_used_size[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_other_amount_empties[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_other_amount_first[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_request_t __po_hi_vt_atm_other_amount_recent[__po_hi_vt_atm_other_amount_nb_ports];
__po_hi_port_t __po_hi_vt_atm_other_amount_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_other_amount_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_other_amount_history[1];
__po_hi_port_id_t __po_hi_vt_atm_other_amount_n_dest[__po_hi_vt_atm_other_amount_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_other_amount_fifo_size[__po_hi_vt_atm_other_amount_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_other_amount_destinations[__po_hi_vt_atm_other_amount_nb_ports] = {NULL,__po_hi_vt_atm_other_amount_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_other_amount_outport_transaction_vt_local_destinations,__po_hi_vt_atm_other_amount_outport_display_vt_local_destinations,__po_hi_vt_atm_other_amount_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_other_amount_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_other_amount
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_other_amount_deliver) stores the incoming request for the 
 * taskvt_atm_other_amount
 */
void vt_atm_other_amount_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_other_amount_global_inport_artificial_other_amount:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_other_amount_k, vt_atm_other_amount_local_inport_artificial_other_amount, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_other_amount_job (void)
 * \brief Function executed by the task vt_atm_other_amount
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_other_amount*/
extern void po_hi_c_vt_atm_other_amount_artificial_other_amount 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_other_amount);
void* vt_atm_other_amount_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_other_amount_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_other_amount_k, __po_hi_vt_atm_other_amount_nb_ports, __po_hi_vt_atm_other_amount_queue, __po_hi_vt_atm_other_amount_fifo_size, __po_hi_vt_atm_other_amount_first, __po_hi_vt_atm_other_amount_offsets, __po_hi_vt_atm_other_amount_woffsets, __po_hi_vt_atm_other_amount_n_dest, __po_hi_vt_atm_other_amount_destinations, __po_hi_vt_atm_other_amount_used_size, __po_hi_vt_atm_other_amount_history, __po_hi_vt_atm_other_amount_recent, __po_hi_vt_atm_other_amount_empties, __po_hi_vt_atm_other_amount_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_other_amount_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_other_amount_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_other_amount_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_other_amount_local_inport_artificial_other_amount:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_other_amount_k, vt_atm_other_amount_local_inport_artificial_other_amount))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_other_amount_k, vt_atm_other_amount_local_inport_artificial_other_amount, &(inport_artificial_other_amount_request));
          __po_hi_gqueue_next_value (chip_vt_atm_other_amount_k, vt_atm_other_amount_local_inport_artificial_other_amount);

        }

        po_hi_c_vt_atm_other_amount_artificial_other_amount (chip_vt_atm_other_amount_k, inport_artificial_other_amount_request.vars.vt_atm_other_amount_global_inport_artificial_other_amount.vt_atm_other_amount_global_inport_artificial_other_amount);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_other_amount_k, vt_atm_other_amount_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_other_amount_k, vt_atm_other_amount_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_other_amount_k, vt_atm_other_amount_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_other_amount_k, vt_atm_other_amount_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_other_amount_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_digit_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_digit_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_digit_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_digit_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_digit_woffsets[__po_hi_vt_atm_digit_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_digit_offsets[__po_hi_vt_atm_digit_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_digit_used_size[__po_hi_vt_atm_digit_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_digit_empties[__po_hi_vt_atm_digit_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_digit_first[__po_hi_vt_atm_digit_nb_ports];
__po_hi_request_t __po_hi_vt_atm_digit_recent[__po_hi_vt_atm_digit_nb_ports];
__po_hi_port_t __po_hi_vt_atm_digit_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_digit_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_digit_history[1];
__po_hi_port_id_t __po_hi_vt_atm_digit_n_dest[__po_hi_vt_atm_digit_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_digit_fifo_size[__po_hi_vt_atm_digit_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_digit_destinations[__po_hi_vt_atm_digit_nb_ports] = {NULL,__po_hi_vt_atm_digit_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_digit_outport_transaction_vt_local_destinations,__po_hi_vt_atm_digit_outport_display_vt_local_destinations,__po_hi_vt_atm_digit_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_digit_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_digit
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_digit_deliver) stores the incoming request for the taskvt_atm_digit
 */
void vt_atm_digit_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_digit_global_inport_artificial_digit:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_digit_k, vt_atm_digit_local_inport_artificial_digit, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_digit_job (void)
 * \brief Function executed by the task vt_atm_digit
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_digit*/
extern void po_hi_c_vt_atm_digit_artificial_digit 
    (__po_hi_task_id self,
    dataview__num_buffer_impl inport_artificial_digit);
void* vt_atm_digit_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_digit_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_digit_k, __po_hi_vt_atm_digit_nb_ports, __po_hi_vt_atm_digit_queue, __po_hi_vt_atm_digit_fifo_size, __po_hi_vt_atm_digit_first, __po_hi_vt_atm_digit_offsets, __po_hi_vt_atm_digit_woffsets, __po_hi_vt_atm_digit_n_dest, __po_hi_vt_atm_digit_destinations, __po_hi_vt_atm_digit_used_size, __po_hi_vt_atm_digit_history, __po_hi_vt_atm_digit_recent, __po_hi_vt_atm_digit_empties, __po_hi_vt_atm_digit_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_digit_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_digit_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_digit_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_digit_local_inport_artificial_digit:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_digit_k, vt_atm_digit_local_inport_artificial_digit))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_digit_k, vt_atm_digit_local_inport_artificial_digit, &(inport_artificial_digit_request));
          __po_hi_gqueue_next_value (chip_vt_atm_digit_k, vt_atm_digit_local_inport_artificial_digit);

        }

        po_hi_c_vt_atm_digit_artificial_digit (chip_vt_atm_digit_k, inport_artificial_digit_request.vars.vt_atm_digit_global_inport_artificial_digit.vt_atm_digit_global_inport_artificial_digit);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_digit_k, vt_atm_digit_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_digit_k, vt_atm_digit_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_digit_k, vt_atm_digit_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_digit_k, vt_atm_digit_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_digit_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_ok_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_ok_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_ok_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_ok_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_ok_woffsets[__po_hi_vt_atm_ok_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_ok_offsets[__po_hi_vt_atm_ok_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_ok_used_size[__po_hi_vt_atm_ok_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_ok_empties[__po_hi_vt_atm_ok_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_ok_first[__po_hi_vt_atm_ok_nb_ports];
__po_hi_request_t __po_hi_vt_atm_ok_recent[__po_hi_vt_atm_ok_nb_ports];
__po_hi_port_t __po_hi_vt_atm_ok_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_ok_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_ok_history[1];
__po_hi_port_id_t __po_hi_vt_atm_ok_n_dest[__po_hi_vt_atm_ok_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_ok_fifo_size[__po_hi_vt_atm_ok_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_ok_destinations[__po_hi_vt_atm_ok_nb_ports] = {NULL,__po_hi_vt_atm_ok_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_ok_outport_transaction_vt_local_destinations,__po_hi_vt_atm_ok_outport_display_vt_local_destinations,__po_hi_vt_atm_ok_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_ok_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_ok
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_ok_deliver) stores the incoming request for the taskvt_atm_ok
 */
void vt_atm_ok_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_ok_global_inport_artificial_ok:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_ok_k, vt_atm_ok_local_inport_artificial_ok, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_ok_job (void)
 * \brief Function executed by the task vt_atm_ok
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_ok*/
extern void po_hi_c_vt_atm_ok_artificial_ok 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_ok);
void* vt_atm_ok_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_ok_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_ok_k, __po_hi_vt_atm_ok_nb_ports, __po_hi_vt_atm_ok_queue, __po_hi_vt_atm_ok_fifo_size, __po_hi_vt_atm_ok_first, __po_hi_vt_atm_ok_offsets, __po_hi_vt_atm_ok_woffsets, __po_hi_vt_atm_ok_n_dest, __po_hi_vt_atm_ok_destinations, __po_hi_vt_atm_ok_used_size, __po_hi_vt_atm_ok_history, __po_hi_vt_atm_ok_recent, __po_hi_vt_atm_ok_empties, __po_hi_vt_atm_ok_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_ok_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_ok_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_ok_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_ok_local_inport_artificial_ok:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_ok_k, vt_atm_ok_local_inport_artificial_ok))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_ok_k, vt_atm_ok_local_inport_artificial_ok, &(inport_artificial_ok_request));
          __po_hi_gqueue_next_value (chip_vt_atm_ok_k, vt_atm_ok_local_inport_artificial_ok);

        }

        po_hi_c_vt_atm_ok_artificial_ok (chip_vt_atm_ok_k, inport_artificial_ok_request.vars.vt_atm_ok_global_inport_artificial_ok.vt_atm_ok_global_inport_artificial_ok);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_ok_k, vt_atm_ok_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_ok_k, vt_atm_ok_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_ok_k, vt_atm_ok_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_ok_k, vt_atm_ok_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_ok_k);
  }
}

__po_hi_port_t __po_hi_vt_atm_transaction_succeseeded_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_t __po_hi_vt_atm_transaction_succeseeded_outport_transaction_vt_local_destinations[1] = {vt_gui_transaction_global_inport_artificial_transaction};
__po_hi_port_t __po_hi_vt_atm_transaction_succeseeded_outport_display_vt_local_destinations[1] = {vt_gui_display_global_inport_artificial_display};
__po_hi_port_t __po_hi_vt_atm_transaction_succeseeded_outport_eject_card_vt_local_destinations[1] = {vt_gui_eject_card_global_inport_artificial_eject_card};
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_woffsets[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_offsets[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_used_size[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_empties[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_first[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_request_t __po_hi_vt_atm_transaction_succeseeded_recent[__po_hi_vt_atm_transaction_succeseeded_nb_ports];
__po_hi_port_t __po_hi_vt_atm_transaction_succeseeded_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_atm_transaction_succeseeded_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_atm_transaction_succeseeded_history[1];
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_n_dest[__po_hi_vt_atm_transaction_succeseeded_nb_ports] = {0,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_atm_transaction_succeseeded_fifo_size[__po_hi_vt_atm_transaction_succeseeded_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_atm_transaction_succeseeded_destinations[__po_hi_vt_atm_transaction_succeseeded_nb_ports] = {NULL,__po_hi_vt_atm_transaction_succeseeded_outport_out_msg_vt_local_destinations,__po_hi_vt_atm_transaction_succeseeded_outport_transaction_vt_local_destinations,__po_hi_vt_atm_transaction_succeseeded_outport_display_vt_local_destinations,__po_hi_vt_atm_transaction_succeseeded_outport_eject_card_vt_local_destinations};

/*!
 * \fn void vt_atm_transaction_succeseeded_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_atm_transaction_succeseeded
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_atm_transaction_succeseeded_deliver) stores the incoming request for 
 * the taskvt_atm_transaction_succeseeded
 */
void vt_atm_transaction_succeseeded_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded:
    {
      __po_hi_gqueue_store_in (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_local_inport_artificial_transaction_succeseeded, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_atm_transaction_succeseeded_job (void)
 * \brief Function executed by the task vt_atm_transaction_succeseeded
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_atm_transaction_succeseeded*/
extern void po_hi_c_vt_atm_transaction_succeseeded_artificial_transaction_succeseeded 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_transaction_succeseeded);
void* vt_atm_transaction_succeseeded_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_transaction_succeseeded_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_atm_transaction_succeseeded_k, __po_hi_vt_atm_transaction_succeseeded_nb_ports, __po_hi_vt_atm_transaction_succeseeded_queue, __po_hi_vt_atm_transaction_succeseeded_fifo_size, __po_hi_vt_atm_transaction_succeseeded_first, __po_hi_vt_atm_transaction_succeseeded_offsets, __po_hi_vt_atm_transaction_succeseeded_woffsets, __po_hi_vt_atm_transaction_succeseeded_n_dest, __po_hi_vt_atm_transaction_succeseeded_destinations, __po_hi_vt_atm_transaction_succeseeded_used_size, __po_hi_vt_atm_transaction_succeseeded_history, __po_hi_vt_atm_transaction_succeseeded_recent, __po_hi_vt_atm_transaction_succeseeded_empties, __po_hi_vt_atm_transaction_succeseeded_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_atm_transaction_succeseeded_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_atm_transaction_succeseeded_k, &(port));
    __po_hi_compute_next_period (chip_vt_atm_transaction_succeseeded_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_atm_transaction_succeseeded_local_inport_artificial_transaction_succeseeded:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_local_inport_artificial_transaction_succeseeded))
        {
                  __po_hi_gqueue_get_value (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_local_inport_artificial_transaction_succeseeded, &(inport_artificial_transaction_succeseeded_request));
          __po_hi_gqueue_next_value (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_local_inport_artificial_transaction_succeseeded);

        }

        po_hi_c_vt_atm_transaction_succeseeded_artificial_transaction_succeseeded (chip_vt_atm_transaction_succeseeded_k, inport_artificial_transaction_succeseeded_request.vars.vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded.vt_atm_transaction_succeseeded_global_inport_artificial_transaction_succeseeded);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_global_outport_out_msg_vt);
    error =
     __po_hi_send_output (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_global_outport_transaction_vt);
    error =
     __po_hi_send_output (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_global_outport_display_vt);
    error =
     __po_hi_send_output (chip_vt_atm_transaction_succeseeded_k, vt_atm_transaction_succeseeded_global_outport_eject_card_vt);
    __po_hi_wait_for_next_period (chip_vt_atm_transaction_succeseeded_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_vt_gui_transaction_k_entity:
    {
      vt_gui_transaction_deliver (request);

      break;
    }
    case chip_vt_gui_display_k_entity:
    {
      vt_gui_display_deliver (request);

      break;
    }
    case chip_vt_gui_eject_card_k_entity:
    {
      vt_gui_eject_card_deliver (request);

      break;
    }
    case chip_vt_gui_out_msg_k_entity:
    {
      vt_gui_out_msg_deliver (request);

      break;
    }
    case chip_vt_atm_accept_card_k_entity:
    {
      vt_atm_accept_card_deliver (request);

      break;
    }
    case chip_vt_atm_reject_transaction_k_entity:
    {
      vt_atm_reject_transaction_deliver (request);

      break;
    }
    case chip_vt_atm_out_of_service_k_entity:
    {
      vt_atm_out_of_service_deliver (request);

      break;
    }
    case chip_vt_atm_abort_out_k_entity:
    {
      vt_atm_abort_out_deliver (request);

      break;
    }
    case chip_vt_atm_amount_k_entity:
    {
      vt_atm_amount_deliver (request);

      break;
    }
    case chip_vt_atm_other_amount_k_entity:
    {
      vt_atm_other_amount_deliver (request);

      break;
    }
    case chip_vt_atm_digit_k_entity:
    {
      vt_atm_digit_deliver (request);

      break;
    }
    case chip_vt_atm_ok_k_entity:
    {
      vt_atm_ok_deliver (request);

      break;
    }
    case chip_vt_atm_transaction_succeseeded_k_entity:
    {
      vt_atm_transaction_succeseeded_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


