#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
__po_hi_port_t __po_hi_initsys_outport_outmsg_local_destinations[1] = {vt_gui_outmsg_global_inport_artificial_outmsg};
__po_hi_port_id_t __po_hi_initsys_woffsets[__po_hi_initsys_nb_ports];
__po_hi_port_id_t __po_hi_initsys_offsets[__po_hi_initsys_nb_ports];
__po_hi_port_id_t __po_hi_initsys_used_size[__po_hi_initsys_nb_ports];
__po_hi_port_id_t __po_hi_initsys_empties[__po_hi_initsys_nb_ports];
__po_hi_port_id_t __po_hi_initsys_first[__po_hi_initsys_nb_ports];
__po_hi_request_t __po_hi_initsys_recent[__po_hi_initsys_nb_ports];
__po_hi_port_t __po_hi_initsys_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_initsys_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_initsys_history[1];
__po_hi_port_id_t __po_hi_initsys_n_dest[__po_hi_initsys_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_initsys_fifo_size[__po_hi_initsys_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_initsys_destinations[__po_hi_initsys_nb_ports] = {NULL,__po_hi_initsys_outport_outmsg_local_destinations};

/*!
 * \fn void initsys_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task initsys
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (initsys_deliver) stores the incoming request for the taskinitsys
 */
void initsys_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case initsys_global_inport_inmsg:
    {
      __po_hi_gqueue_store_in (chip_initsys_k, initsys_local_inport_inmsg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* initsys_job (void)
 * \brief Function executed by the task initsys
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : initsys*/
extern void po_hi_c_initsys_inmsg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_inmsg);
void* initsys_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_inmsg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_initsys_k, __po_hi_initsys_nb_ports, __po_hi_initsys_queue, __po_hi_initsys_fifo_size, __po_hi_initsys_first, __po_hi_initsys_offsets, __po_hi_initsys_woffsets, __po_hi_initsys_n_dest, __po_hi_initsys_destinations, __po_hi_initsys_used_size, __po_hi_initsys_history, __po_hi_initsys_recent, __po_hi_initsys_empties, __po_hi_initsys_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_initsys_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_initsys_k, &(port));
    __po_hi_compute_next_period (chip_initsys_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case initsys_local_inport_inmsg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_initsys_k, initsys_local_inport_inmsg))
        {
                  __po_hi_gqueue_get_value (chip_initsys_k, initsys_local_inport_inmsg, &(inport_inmsg_request));
          __po_hi_gqueue_next_value (chip_initsys_k, initsys_local_inport_inmsg);

        }

        po_hi_c_initsys_inmsg (chip_initsys_k, inport_inmsg_request.vars.initsys_global_inport_inmsg.initsys_global_inport_inmsg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_initsys_k, initsys_global_outport_outmsg);
    __po_hi_wait_for_next_period (chip_initsys_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_outmsg_outport_inmsg_vt_local_destinations[1] = {initsys_global_inport_inmsg};
__po_hi_port_id_t __po_hi_vt_gui_outmsg_woffsets[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outmsg_offsets[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outmsg_used_size[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outmsg_empties[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outmsg_first[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_outmsg_recent[__po_hi_vt_gui_outmsg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_outmsg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_outmsg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_outmsg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_outmsg_n_dest[__po_hi_vt_gui_outmsg_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_gui_outmsg_fifo_size[__po_hi_vt_gui_outmsg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_outmsg_destinations[__po_hi_vt_gui_outmsg_nb_ports] = {NULL,__po_hi_vt_gui_outmsg_outport_inmsg_vt_local_destinations};

/*!
 * \fn void vt_gui_outmsg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_outmsg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_outmsg_deliver) stores the incoming request for the 
 * taskvt_gui_outmsg
 */
void vt_gui_outmsg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_outmsg_global_inport_artificial_outmsg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_outmsg_k, vt_gui_outmsg_local_inport_artificial_outmsg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_outmsg_job (void)
 * \brief Function executed by the task vt_gui_outmsg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_outmsg*/
extern void po_hi_c_vt_gui_outmsg_artificial_outmsg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_outmsg);
void* vt_gui_outmsg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_outmsg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_outmsg_k, __po_hi_vt_gui_outmsg_nb_ports, __po_hi_vt_gui_outmsg_queue, __po_hi_vt_gui_outmsg_fifo_size, __po_hi_vt_gui_outmsg_first, __po_hi_vt_gui_outmsg_offsets, __po_hi_vt_gui_outmsg_woffsets, __po_hi_vt_gui_outmsg_n_dest, __po_hi_vt_gui_outmsg_destinations, __po_hi_vt_gui_outmsg_used_size, __po_hi_vt_gui_outmsg_history, __po_hi_vt_gui_outmsg_recent, __po_hi_vt_gui_outmsg_empties, __po_hi_vt_gui_outmsg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_outmsg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_outmsg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_outmsg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_outmsg_local_inport_artificial_outmsg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_outmsg_k, vt_gui_outmsg_local_inport_artificial_outmsg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_outmsg_k, vt_gui_outmsg_local_inport_artificial_outmsg, &(inport_artificial_outmsg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_outmsg_k, vt_gui_outmsg_local_inport_artificial_outmsg);

        }

        po_hi_c_vt_gui_outmsg_artificial_outmsg (chip_vt_gui_outmsg_k, inport_artificial_outmsg_request.vars.vt_gui_outmsg_global_inport_artificial_outmsg.vt_gui_outmsg_global_inport_artificial_outmsg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_outmsg_k, vt_gui_outmsg_global_outport_inmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_outmsg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_inmsg_vt_local_destinations[1] = {initsys_global_inport_inmsg};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_inmsg_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_inmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_initsys_k_entity:
    {
      initsys_deliver (request);

      break;
    }
    case chip_vt_gui_outmsg_k_entity:
    {
      vt_gui_outmsg_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


