#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
extern process_package__taste_protected_object coffee_protected;
extern process_package__taste_protected_object chip_timer_manager_protected;
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_get_init_tmpr_vt_local_destinations[1] = {vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_get_init_water_vt_local_destinations[1] = {vt_coffee_get_init_water_global_inport_artificial_get_init_water};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_for_water_vt_local_destinations[1] = {vt_coffee_for_water_global_inport_artificial_for_water};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_for_water_tmpr_vt_local_destinations[1] = {vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_for_coffee_vt_local_destinations[1] = {vt_coffee_for_coffee_global_inport_artificial_for_coffee};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_for_ticking_vt_local_destinations[1] = {vt_coffee_for_ticking_global_inport_artificial_for_ticking};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_woffsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_offsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_used_size[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_empties[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_first[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_out_msg_recent[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_out_msg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_out_msg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_out_msg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_n_dest[__po_hi_vt_gui_out_msg_nb_ports] = {0,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_fifo_size[__po_hi_vt_gui_out_msg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_out_msg_destinations[__po_hi_vt_gui_out_msg_nb_ports] = {NULL,__po_hi_vt_gui_out_msg_outport_get_init_tmpr_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_get_init_water_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_for_water_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_for_water_tmpr_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_for_coffee_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_for_ticking_vt_local_destinations};

/*!
 * \fn void vt_gui_out_msg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_out_msg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_out_msg_deliver) stores the incoming request for the 
 * taskvt_gui_out_msg
 */
void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_out_msg_job (void)
 * \brief Function executed by the task vt_gui_out_msg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_out_msg*/
extern void po_hi_c_vt_gui_out_msg_artificial_out_msg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_out_msg);
void* vt_gui_out_msg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_out_msg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_out_msg_k, __po_hi_vt_gui_out_msg_nb_ports, __po_hi_vt_gui_out_msg_queue, __po_hi_vt_gui_out_msg_fifo_size, __po_hi_vt_gui_out_msg_first, __po_hi_vt_gui_out_msg_offsets, __po_hi_vt_gui_out_msg_woffsets, __po_hi_vt_gui_out_msg_n_dest, __po_hi_vt_gui_out_msg_destinations, __po_hi_vt_gui_out_msg_used_size, __po_hi_vt_gui_out_msg_history, __po_hi_vt_gui_out_msg_recent, __po_hi_vt_gui_out_msg_empties, __po_hi_vt_gui_out_msg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_out_msg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_out_msg_local_inport_artificial_out_msg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, &(inport_artificial_out_msg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg);

        }

        po_hi_c_vt_gui_out_msg_artificial_out_msg (chip_vt_gui_out_msg_k, inport_artificial_out_msg_request.vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_get_init_tmpr_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_get_init_water_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_for_water_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_for_water_tmpr_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_for_coffee_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_for_ticking_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_out_msg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt_local_destinations[1] = {vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_get_init_water_vt_local_destinations[1] = {vt_coffee_get_init_water_global_inport_artificial_get_init_water};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_for_water_vt_local_destinations[1] = {vt_coffee_for_water_global_inport_artificial_for_water};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt_local_destinations[1] = {vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_for_coffee_vt_local_destinations[1] = {vt_coffee_for_coffee_global_inport_artificial_for_coffee};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_for_ticking_vt_local_destinations[1] = {vt_coffee_for_ticking_global_inport_artificial_for_ticking};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_get_init_water_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_for_water_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_for_coffee_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_for_ticking_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_get_init_water_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_for_water_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_for_coffee_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_for_ticking_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_get_init_tmpr_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_woffsets[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_offsets[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_used_size[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_empties[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_first[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_get_init_tmpr_recent[__po_hi_vt_coffee_get_init_tmpr_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_get_init_tmpr_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_get_init_tmpr_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_get_init_tmpr_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_n_dest[__po_hi_vt_coffee_get_init_tmpr_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_get_init_tmpr_fifo_size[__po_hi_vt_coffee_get_init_tmpr_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_get_init_tmpr_destinations[__po_hi_vt_coffee_get_init_tmpr_nb_ports] = {NULL,__po_hi_vt_coffee_get_init_tmpr_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_get_init_tmpr_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_get_init_tmpr
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_get_init_tmpr_deliver) stores the incoming request for the 
 * taskvt_coffee_get_init_tmpr
 */
void vt_coffee_get_init_tmpr_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_get_init_tmpr_k, vt_coffee_get_init_tmpr_local_inport_artificial_get_init_tmpr, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_get_init_tmpr_job (void)
 * \brief Function executed by the task vt_coffee_get_init_tmpr
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_get_init_tmpr*/
extern void po_hi_c_vt_coffee_get_init_tmpr_artificial_get_init_tmpr 
    (__po_hi_task_id self,
    dataview__t_int32_buffer_impl inport_artificial_get_init_tmpr);
void* vt_coffee_get_init_tmpr_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_get_init_tmpr_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_get_init_tmpr_k, __po_hi_vt_coffee_get_init_tmpr_nb_ports, __po_hi_vt_coffee_get_init_tmpr_queue, __po_hi_vt_coffee_get_init_tmpr_fifo_size, __po_hi_vt_coffee_get_init_tmpr_first, __po_hi_vt_coffee_get_init_tmpr_offsets, __po_hi_vt_coffee_get_init_tmpr_woffsets, __po_hi_vt_coffee_get_init_tmpr_n_dest, __po_hi_vt_coffee_get_init_tmpr_destinations, __po_hi_vt_coffee_get_init_tmpr_used_size, __po_hi_vt_coffee_get_init_tmpr_history, __po_hi_vt_coffee_get_init_tmpr_recent, __po_hi_vt_coffee_get_init_tmpr_empties, __po_hi_vt_coffee_get_init_tmpr_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_get_init_tmpr_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_get_init_tmpr_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_get_init_tmpr_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_get_init_tmpr_local_inport_artificial_get_init_tmpr:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_get_init_tmpr_k, vt_coffee_get_init_tmpr_local_inport_artificial_get_init_tmpr))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_get_init_tmpr_k, vt_coffee_get_init_tmpr_local_inport_artificial_get_init_tmpr, &(inport_artificial_get_init_tmpr_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_get_init_tmpr_k, vt_coffee_get_init_tmpr_local_inport_artificial_get_init_tmpr);

        }

        po_hi_c_vt_coffee_get_init_tmpr_artificial_get_init_tmpr (chip_vt_coffee_get_init_tmpr_k, inport_artificial_get_init_tmpr_request.vars.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_get_init_tmpr_k, vt_coffee_get_init_tmpr_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_get_init_tmpr_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_get_init_water_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_woffsets[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_offsets[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_used_size[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_empties[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_first[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_get_init_water_recent[__po_hi_vt_coffee_get_init_water_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_get_init_water_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_get_init_water_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_get_init_water_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_n_dest[__po_hi_vt_coffee_get_init_water_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_get_init_water_fifo_size[__po_hi_vt_coffee_get_init_water_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_get_init_water_destinations[__po_hi_vt_coffee_get_init_water_nb_ports] = {NULL,__po_hi_vt_coffee_get_init_water_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_get_init_water_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_get_init_water
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_get_init_water_deliver) stores the incoming request for the 
 * taskvt_coffee_get_init_water
 */
void vt_coffee_get_init_water_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_get_init_water_global_inport_artificial_get_init_water:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_get_init_water_k, vt_coffee_get_init_water_local_inport_artificial_get_init_water, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_get_init_water_job (void)
 * \brief Function executed by the task vt_coffee_get_init_water
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_get_init_water*/
extern void po_hi_c_vt_coffee_get_init_water_artificial_get_init_water 
    (__po_hi_task_id self,
    dataview__t_int32_buffer_impl inport_artificial_get_init_water);
void* vt_coffee_get_init_water_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_get_init_water_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_get_init_water_k, __po_hi_vt_coffee_get_init_water_nb_ports, __po_hi_vt_coffee_get_init_water_queue, __po_hi_vt_coffee_get_init_water_fifo_size, __po_hi_vt_coffee_get_init_water_first, __po_hi_vt_coffee_get_init_water_offsets, __po_hi_vt_coffee_get_init_water_woffsets, __po_hi_vt_coffee_get_init_water_n_dest, __po_hi_vt_coffee_get_init_water_destinations, __po_hi_vt_coffee_get_init_water_used_size, __po_hi_vt_coffee_get_init_water_history, __po_hi_vt_coffee_get_init_water_recent, __po_hi_vt_coffee_get_init_water_empties, __po_hi_vt_coffee_get_init_water_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_get_init_water_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_get_init_water_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_get_init_water_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_get_init_water_local_inport_artificial_get_init_water:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_get_init_water_k, vt_coffee_get_init_water_local_inport_artificial_get_init_water))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_get_init_water_k, vt_coffee_get_init_water_local_inport_artificial_get_init_water, &(inport_artificial_get_init_water_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_get_init_water_k, vt_coffee_get_init_water_local_inport_artificial_get_init_water);

        }

        po_hi_c_vt_coffee_get_init_water_artificial_get_init_water (chip_vt_coffee_get_init_water_k, inport_artificial_get_init_water_request.vars.vt_coffee_get_init_water_global_inport_artificial_get_init_water.vt_coffee_get_init_water_global_inport_artificial_get_init_water);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_get_init_water_k, vt_coffee_get_init_water_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_get_init_water_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_for_water_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_for_water_woffsets[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_offsets[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_used_size[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_empties[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_first[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_for_water_recent[__po_hi_vt_coffee_for_water_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_for_water_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_for_water_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_for_water_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_n_dest[__po_hi_vt_coffee_for_water_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_for_water_fifo_size[__po_hi_vt_coffee_for_water_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_for_water_destinations[__po_hi_vt_coffee_for_water_nb_ports] = {NULL,__po_hi_vt_coffee_for_water_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_for_water_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_for_water
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_for_water_deliver) stores the incoming request for the 
 * taskvt_coffee_for_water
 */
void vt_coffee_for_water_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_for_water_global_inport_artificial_for_water:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_for_water_k, vt_coffee_for_water_local_inport_artificial_for_water, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_for_water_job (void)
 * \brief Function executed by the task vt_coffee_for_water
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_for_water*/
extern void po_hi_c_vt_coffee_for_water_artificial_for_water 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_for_water);
void* vt_coffee_for_water_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_for_water_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_for_water_k, __po_hi_vt_coffee_for_water_nb_ports, __po_hi_vt_coffee_for_water_queue, __po_hi_vt_coffee_for_water_fifo_size, __po_hi_vt_coffee_for_water_first, __po_hi_vt_coffee_for_water_offsets, __po_hi_vt_coffee_for_water_woffsets, __po_hi_vt_coffee_for_water_n_dest, __po_hi_vt_coffee_for_water_destinations, __po_hi_vt_coffee_for_water_used_size, __po_hi_vt_coffee_for_water_history, __po_hi_vt_coffee_for_water_recent, __po_hi_vt_coffee_for_water_empties, __po_hi_vt_coffee_for_water_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_for_water_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_for_water_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_for_water_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_for_water_local_inport_artificial_for_water:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_for_water_k, vt_coffee_for_water_local_inport_artificial_for_water))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_for_water_k, vt_coffee_for_water_local_inport_artificial_for_water, &(inport_artificial_for_water_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_for_water_k, vt_coffee_for_water_local_inport_artificial_for_water);

        }

        po_hi_c_vt_coffee_for_water_artificial_for_water (chip_vt_coffee_for_water_k, inport_artificial_for_water_request.vars.vt_coffee_for_water_global_inport_artificial_for_water.vt_coffee_for_water_global_inport_artificial_for_water);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_for_water_k, vt_coffee_for_water_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_for_water_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_for_water_tmpr_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_woffsets[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_offsets[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_used_size[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_empties[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_first[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_for_water_tmpr_recent[__po_hi_vt_coffee_for_water_tmpr_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_for_water_tmpr_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_for_water_tmpr_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_for_water_tmpr_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_n_dest[__po_hi_vt_coffee_for_water_tmpr_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_for_water_tmpr_fifo_size[__po_hi_vt_coffee_for_water_tmpr_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_for_water_tmpr_destinations[__po_hi_vt_coffee_for_water_tmpr_nb_ports] = {NULL,__po_hi_vt_coffee_for_water_tmpr_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_for_water_tmpr_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_for_water_tmpr
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_for_water_tmpr_deliver) stores the incoming request for the 
 * taskvt_coffee_for_water_tmpr
 */
void vt_coffee_for_water_tmpr_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_for_water_tmpr_k, vt_coffee_for_water_tmpr_local_inport_artificial_for_water_tmpr, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_for_water_tmpr_job (void)
 * \brief Function executed by the task vt_coffee_for_water_tmpr
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_for_water_tmpr*/
extern void po_hi_c_vt_coffee_for_water_tmpr_artificial_for_water_tmpr 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_for_water_tmpr);
void* vt_coffee_for_water_tmpr_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_for_water_tmpr_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_for_water_tmpr_k, __po_hi_vt_coffee_for_water_tmpr_nb_ports, __po_hi_vt_coffee_for_water_tmpr_queue, __po_hi_vt_coffee_for_water_tmpr_fifo_size, __po_hi_vt_coffee_for_water_tmpr_first, __po_hi_vt_coffee_for_water_tmpr_offsets, __po_hi_vt_coffee_for_water_tmpr_woffsets, __po_hi_vt_coffee_for_water_tmpr_n_dest, __po_hi_vt_coffee_for_water_tmpr_destinations, __po_hi_vt_coffee_for_water_tmpr_used_size, __po_hi_vt_coffee_for_water_tmpr_history, __po_hi_vt_coffee_for_water_tmpr_recent, __po_hi_vt_coffee_for_water_tmpr_empties, __po_hi_vt_coffee_for_water_tmpr_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_for_water_tmpr_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_for_water_tmpr_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_for_water_tmpr_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_for_water_tmpr_local_inport_artificial_for_water_tmpr:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_for_water_tmpr_k, vt_coffee_for_water_tmpr_local_inport_artificial_for_water_tmpr))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_for_water_tmpr_k, vt_coffee_for_water_tmpr_local_inport_artificial_for_water_tmpr, &(inport_artificial_for_water_tmpr_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_for_water_tmpr_k, vt_coffee_for_water_tmpr_local_inport_artificial_for_water_tmpr);

        }

        po_hi_c_vt_coffee_for_water_tmpr_artificial_for_water_tmpr (chip_vt_coffee_for_water_tmpr_k, inport_artificial_for_water_tmpr_request.vars.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_for_water_tmpr_k, vt_coffee_for_water_tmpr_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_for_water_tmpr_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_for_coffee_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_woffsets[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_offsets[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_used_size[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_empties[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_first[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_for_coffee_recent[__po_hi_vt_coffee_for_coffee_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_for_coffee_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_for_coffee_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_for_coffee_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_n_dest[__po_hi_vt_coffee_for_coffee_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_for_coffee_fifo_size[__po_hi_vt_coffee_for_coffee_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_for_coffee_destinations[__po_hi_vt_coffee_for_coffee_nb_ports] = {NULL,__po_hi_vt_coffee_for_coffee_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_for_coffee_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_for_coffee
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_for_coffee_deliver) stores the incoming request for the 
 * taskvt_coffee_for_coffee
 */
void vt_coffee_for_coffee_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_for_coffee_global_inport_artificial_for_coffee:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_for_coffee_k, vt_coffee_for_coffee_local_inport_artificial_for_coffee, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_for_coffee_job (void)
 * \brief Function executed by the task vt_coffee_for_coffee
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_for_coffee*/
extern void po_hi_c_vt_coffee_for_coffee_artificial_for_coffee 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_for_coffee);
void* vt_coffee_for_coffee_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_for_coffee_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_for_coffee_k, __po_hi_vt_coffee_for_coffee_nb_ports, __po_hi_vt_coffee_for_coffee_queue, __po_hi_vt_coffee_for_coffee_fifo_size, __po_hi_vt_coffee_for_coffee_first, __po_hi_vt_coffee_for_coffee_offsets, __po_hi_vt_coffee_for_coffee_woffsets, __po_hi_vt_coffee_for_coffee_n_dest, __po_hi_vt_coffee_for_coffee_destinations, __po_hi_vt_coffee_for_coffee_used_size, __po_hi_vt_coffee_for_coffee_history, __po_hi_vt_coffee_for_coffee_recent, __po_hi_vt_coffee_for_coffee_empties, __po_hi_vt_coffee_for_coffee_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_for_coffee_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_for_coffee_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_for_coffee_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_for_coffee_local_inport_artificial_for_coffee:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_for_coffee_k, vt_coffee_for_coffee_local_inport_artificial_for_coffee))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_for_coffee_k, vt_coffee_for_coffee_local_inport_artificial_for_coffee, &(inport_artificial_for_coffee_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_for_coffee_k, vt_coffee_for_coffee_local_inport_artificial_for_coffee);

        }

        po_hi_c_vt_coffee_for_coffee_artificial_for_coffee (chip_vt_coffee_for_coffee_k, inport_artificial_for_coffee_request.vars.vt_coffee_for_coffee_global_inport_artificial_for_coffee.vt_coffee_for_coffee_global_inport_artificial_for_coffee);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_for_coffee_k, vt_coffee_for_coffee_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_for_coffee_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_for_ticking_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_woffsets[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_offsets[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_used_size[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_empties[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_first[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_for_ticking_recent[__po_hi_vt_coffee_for_ticking_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_for_ticking_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_for_ticking_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_for_ticking_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_n_dest[__po_hi_vt_coffee_for_ticking_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_for_ticking_fifo_size[__po_hi_vt_coffee_for_ticking_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_for_ticking_destinations[__po_hi_vt_coffee_for_ticking_nb_ports] = {NULL,__po_hi_vt_coffee_for_ticking_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_for_ticking_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_for_ticking
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_for_ticking_deliver) stores the incoming request for the 
 * taskvt_coffee_for_ticking
 */
void vt_coffee_for_ticking_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_for_ticking_global_inport_artificial_for_ticking:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_for_ticking_k, vt_coffee_for_ticking_local_inport_artificial_for_ticking, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_for_ticking_job (void)
 * \brief Function executed by the task vt_coffee_for_ticking
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_for_ticking*/
extern void po_hi_c_vt_coffee_for_ticking_artificial_for_ticking 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_for_ticking);
void* vt_coffee_for_ticking_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_for_ticking_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_for_ticking_k, __po_hi_vt_coffee_for_ticking_nb_ports, __po_hi_vt_coffee_for_ticking_queue, __po_hi_vt_coffee_for_ticking_fifo_size, __po_hi_vt_coffee_for_ticking_first, __po_hi_vt_coffee_for_ticking_offsets, __po_hi_vt_coffee_for_ticking_woffsets, __po_hi_vt_coffee_for_ticking_n_dest, __po_hi_vt_coffee_for_ticking_destinations, __po_hi_vt_coffee_for_ticking_used_size, __po_hi_vt_coffee_for_ticking_history, __po_hi_vt_coffee_for_ticking_recent, __po_hi_vt_coffee_for_ticking_empties, __po_hi_vt_coffee_for_ticking_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_for_ticking_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_for_ticking_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_for_ticking_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_for_ticking_local_inport_artificial_for_ticking:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_coffee_for_ticking_k, vt_coffee_for_ticking_local_inport_artificial_for_ticking))
        {
                  __po_hi_gqueue_get_value (chip_vt_coffee_for_ticking_k, vt_coffee_for_ticking_local_inport_artificial_for_ticking, &(inport_artificial_for_ticking_request));
          __po_hi_gqueue_next_value (chip_vt_coffee_for_ticking_k, vt_coffee_for_ticking_local_inport_artificial_for_ticking);

        }

        po_hi_c_vt_coffee_for_ticking_artificial_for_ticking (chip_vt_coffee_for_ticking_k, inport_artificial_for_ticking_request.vars.vt_coffee_for_ticking_global_inport_artificial_for_ticking.vt_coffee_for_ticking_global_inport_artificial_for_ticking);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_for_ticking_k, vt_coffee_for_ticking_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_for_ticking_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_tmr_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_tmr_woffsets[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr_offsets[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr_used_size[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr_empties[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr_first[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_tmr_recent[__po_hi_vt_coffee_tmr_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_tmr_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_tmr_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_tmr_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_tmr_n_dest[__po_hi_vt_coffee_tmr_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_tmr_fifo_size[__po_hi_vt_coffee_tmr_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_tmr_destinations[__po_hi_vt_coffee_tmr_nb_ports] = {NULL,__po_hi_vt_coffee_tmr_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_tmr_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_tmr
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_tmr_deliver) stores the incoming request for the 
 * taskvt_coffee_tmr
 */
void vt_coffee_tmr_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_tmr_global_inport_artificial_tmr:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_tmr_k, vt_coffee_tmr_local_inport_artificial_tmr, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_tmr_job (void)
 * \brief Function executed by the task vt_coffee_tmr
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_tmr*/
extern void po_hi_c_vt_coffee_tmr_artificial_tmr 
    (__po_hi_task_id self);
void* vt_coffee_tmr_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_tmr_k, __po_hi_vt_coffee_tmr_nb_ports, __po_hi_vt_coffee_tmr_queue, __po_hi_vt_coffee_tmr_fifo_size, __po_hi_vt_coffee_tmr_first, __po_hi_vt_coffee_tmr_offsets, __po_hi_vt_coffee_tmr_woffsets, __po_hi_vt_coffee_tmr_n_dest, __po_hi_vt_coffee_tmr_destinations, __po_hi_vt_coffee_tmr_used_size, __po_hi_vt_coffee_tmr_history, __po_hi_vt_coffee_tmr_recent, __po_hi_vt_coffee_tmr_empties, __po_hi_vt_coffee_tmr_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_tmr_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_tmr_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_tmr_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_tmr_local_inport_artificial_tmr:
      {
        __po_hi_gqueue_next_value (chip_vt_coffee_tmr_k, vt_coffee_tmr_local_inport_artificial_tmr);

        po_hi_c_vt_coffee_tmr_artificial_tmr (chip_vt_coffee_tmr_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_tmr_k, vt_coffee_tmr_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_tmr_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_tmr1_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_woffsets[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_offsets[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_used_size[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_empties[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_first[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_tmr1_recent[__po_hi_vt_coffee_tmr1_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_tmr1_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_tmr1_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_tmr1_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_n_dest[__po_hi_vt_coffee_tmr1_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_tmr1_fifo_size[__po_hi_vt_coffee_tmr1_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_tmr1_destinations[__po_hi_vt_coffee_tmr1_nb_ports] = {NULL,__po_hi_vt_coffee_tmr1_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_tmr1_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_tmr1
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_tmr1_deliver) stores the incoming request for the 
 * taskvt_coffee_tmr1
 */
void vt_coffee_tmr1_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_tmr1_global_inport_artificial_tmr1:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_tmr1_k, vt_coffee_tmr1_local_inport_artificial_tmr1, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_tmr1_job (void)
 * \brief Function executed by the task vt_coffee_tmr1
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_tmr1*/
extern void po_hi_c_vt_coffee_tmr1_artificial_tmr1 
    (__po_hi_task_id self);
void* vt_coffee_tmr1_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_tmr1_k, __po_hi_vt_coffee_tmr1_nb_ports, __po_hi_vt_coffee_tmr1_queue, __po_hi_vt_coffee_tmr1_fifo_size, __po_hi_vt_coffee_tmr1_first, __po_hi_vt_coffee_tmr1_offsets, __po_hi_vt_coffee_tmr1_woffsets, __po_hi_vt_coffee_tmr1_n_dest, __po_hi_vt_coffee_tmr1_destinations, __po_hi_vt_coffee_tmr1_used_size, __po_hi_vt_coffee_tmr1_history, __po_hi_vt_coffee_tmr1_recent, __po_hi_vt_coffee_tmr1_empties, __po_hi_vt_coffee_tmr1_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_tmr1_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_tmr1_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_tmr1_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_tmr1_local_inport_artificial_tmr1:
      {
        __po_hi_gqueue_next_value (chip_vt_coffee_tmr1_k, vt_coffee_tmr1_local_inport_artificial_tmr1);

        po_hi_c_vt_coffee_tmr1_artificial_tmr1 (chip_vt_coffee_tmr1_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_tmr1_k, vt_coffee_tmr1_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_tmr1_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_tmr2_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_woffsets[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_offsets[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_used_size[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_empties[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_first[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_tmr2_recent[__po_hi_vt_coffee_tmr2_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_tmr2_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_tmr2_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_tmr2_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_n_dest[__po_hi_vt_coffee_tmr2_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_tmr2_fifo_size[__po_hi_vt_coffee_tmr2_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_tmr2_destinations[__po_hi_vt_coffee_tmr2_nb_ports] = {NULL,__po_hi_vt_coffee_tmr2_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_tmr2_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_tmr2
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_tmr2_deliver) stores the incoming request for the 
 * taskvt_coffee_tmr2
 */
void vt_coffee_tmr2_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_tmr2_global_inport_artificial_tmr2:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_tmr2_k, vt_coffee_tmr2_local_inport_artificial_tmr2, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_tmr2_job (void)
 * \brief Function executed by the task vt_coffee_tmr2
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_tmr2*/
extern void po_hi_c_vt_coffee_tmr2_artificial_tmr2 
    (__po_hi_task_id self);
void* vt_coffee_tmr2_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_tmr2_k, __po_hi_vt_coffee_tmr2_nb_ports, __po_hi_vt_coffee_tmr2_queue, __po_hi_vt_coffee_tmr2_fifo_size, __po_hi_vt_coffee_tmr2_first, __po_hi_vt_coffee_tmr2_offsets, __po_hi_vt_coffee_tmr2_woffsets, __po_hi_vt_coffee_tmr2_n_dest, __po_hi_vt_coffee_tmr2_destinations, __po_hi_vt_coffee_tmr2_used_size, __po_hi_vt_coffee_tmr2_history, __po_hi_vt_coffee_tmr2_recent, __po_hi_vt_coffee_tmr2_empties, __po_hi_vt_coffee_tmr2_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_tmr2_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_tmr2_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_tmr2_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_tmr2_local_inport_artificial_tmr2:
      {
        __po_hi_gqueue_next_value (chip_vt_coffee_tmr2_k, vt_coffee_tmr2_local_inport_artificial_tmr2);

        po_hi_c_vt_coffee_tmr2_artificial_tmr2 (chip_vt_coffee_tmr2_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_tmr2_k, vt_coffee_tmr2_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_tmr2_k);
  }
}

__po_hi_port_t __po_hi_vt_coffee_tmr3_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_woffsets[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_offsets[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_used_size[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_empties[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_first[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_request_t __po_hi_vt_coffee_tmr3_recent[__po_hi_vt_coffee_tmr3_nb_ports];
__po_hi_port_t __po_hi_vt_coffee_tmr3_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_coffee_tmr3_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_coffee_tmr3_history[1];
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_n_dest[__po_hi_vt_coffee_tmr3_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_coffee_tmr3_fifo_size[__po_hi_vt_coffee_tmr3_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_coffee_tmr3_destinations[__po_hi_vt_coffee_tmr3_nb_ports] = {NULL,__po_hi_vt_coffee_tmr3_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_coffee_tmr3_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_coffee_tmr3
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_coffee_tmr3_deliver) stores the incoming request for the 
 * taskvt_coffee_tmr3
 */
void vt_coffee_tmr3_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_coffee_tmr3_global_inport_artificial_tmr3:
    {
      __po_hi_gqueue_store_in (chip_vt_coffee_tmr3_k, vt_coffee_tmr3_local_inport_artificial_tmr3, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_coffee_tmr3_job (void)
 * \brief Function executed by the task vt_coffee_tmr3
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_coffee_tmr3*/
extern void po_hi_c_vt_coffee_tmr3_artificial_tmr3 
    (__po_hi_task_id self);
void* vt_coffee_tmr3_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_coffee_tmr3_k, __po_hi_vt_coffee_tmr3_nb_ports, __po_hi_vt_coffee_tmr3_queue, __po_hi_vt_coffee_tmr3_fifo_size, __po_hi_vt_coffee_tmr3_first, __po_hi_vt_coffee_tmr3_offsets, __po_hi_vt_coffee_tmr3_woffsets, __po_hi_vt_coffee_tmr3_n_dest, __po_hi_vt_coffee_tmr3_destinations, __po_hi_vt_coffee_tmr3_used_size, __po_hi_vt_coffee_tmr3_history, __po_hi_vt_coffee_tmr3_recent, __po_hi_vt_coffee_tmr3_empties, __po_hi_vt_coffee_tmr3_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_coffee_tmr3_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_coffee_tmr3_k, &(port));
    __po_hi_compute_next_period (chip_vt_coffee_tmr3_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_coffee_tmr3_local_inport_artificial_tmr3:
      {
        __po_hi_gqueue_next_value (chip_vt_coffee_tmr3_k, vt_coffee_tmr3_local_inport_artificial_tmr3);

        po_hi_c_vt_coffee_tmr3_artificial_tmr3 (chip_vt_coffee_tmr3_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_coffee_tmr3_k, vt_coffee_tmr3_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_coffee_tmr3_k);
  }
}

__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr_vt_local_destinations[1] = {vt_coffee_tmr_global_inport_artificial_tmr};
__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr1_vt_local_destinations[1] = {vt_coffee_tmr1_global_inport_artificial_tmr1};
__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr2_vt_local_destinations[1] = {vt_coffee_tmr2_global_inport_artificial_tmr2};
__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr3_vt_local_destinations[1] = {vt_coffee_tmr3_global_inport_artificial_tmr3};
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_woffsets[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_offsets[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_used_size[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_empties[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_first[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_request_t __po_hi_vt_chip_timer_manager_tick_100ms_recent[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_chip_timer_manager_tick_100ms_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_chip_timer_manager_tick_100ms_history[0];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_n_dest[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {1,1,1,1};
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_fifo_size[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_chip_timer_manager_tick_100ms_destinations[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {__po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr_vt_local_destinations,__po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr1_vt_local_destinations,__po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr2_vt_local_destinations,__po_hi_vt_chip_timer_manager_tick_100ms_outport_coffee_tmr3_vt_local_destinations};

/*!
 * \fn void* vt_chip_timer_manager_tick_100ms_job (void)
 * \brief Function executed by the task vt_chip_timer_manager_tick_100ms
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_chip_timer_manager_tick_100ms*/
extern void po_hi_c_vt_chip_timer_manager_tick_100ms_artificial_tick_100ms 
    (__po_hi_task_id self);
void* vt_chip_timer_manager_tick_100ms_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_chip_timer_manager_tick_100ms_k, __po_hi_vt_chip_timer_manager_tick_100ms_nb_ports, __po_hi_vt_chip_timer_manager_tick_100ms_queue, __po_hi_vt_chip_timer_manager_tick_100ms_fifo_size, __po_hi_vt_chip_timer_manager_tick_100ms_first, __po_hi_vt_chip_timer_manager_tick_100ms_offsets, __po_hi_vt_chip_timer_manager_tick_100ms_woffsets, __po_hi_vt_chip_timer_manager_tick_100ms_n_dest, __po_hi_vt_chip_timer_manager_tick_100ms_destinations, __po_hi_vt_chip_timer_manager_tick_100ms_used_size, __po_hi_vt_chip_timer_manager_tick_100ms_history, __po_hi_vt_chip_timer_manager_tick_100ms_recent, __po_hi_vt_chip_timer_manager_tick_100ms_empties, __po_hi_vt_chip_timer_manager_tick_100ms_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_chip_timer_manager_tick_100ms_artificial_tick_100ms (chip_vt_chip_timer_manager_tick_100ms_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_chip_timer_manager_tick_100ms_k, vt_chip_timer_manager_tick_100ms_global_outport_coffee_tmr_vt);
    error =
     __po_hi_send_output (chip_vt_chip_timer_manager_tick_100ms_k, vt_chip_timer_manager_tick_100ms_global_outport_coffee_tmr1_vt);
    error =
     __po_hi_send_output (chip_vt_chip_timer_manager_tick_100ms_k, vt_chip_timer_manager_tick_100ms_global_outport_coffee_tmr2_vt);
    error =
     __po_hi_send_output (chip_vt_chip_timer_manager_tick_100ms_k, vt_chip_timer_manager_tick_100ms_global_outport_coffee_tmr3_vt);
    __po_hi_wait_for_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_vt_gui_out_msg_k_entity:
    {
      vt_gui_out_msg_deliver (request);

      break;
    }
    case chip_vt_coffee_get_init_tmpr_k_entity:
    {
      vt_coffee_get_init_tmpr_deliver (request);

      break;
    }
    case chip_vt_coffee_get_init_water_k_entity:
    {
      vt_coffee_get_init_water_deliver (request);

      break;
    }
    case chip_vt_coffee_for_water_k_entity:
    {
      vt_coffee_for_water_deliver (request);

      break;
    }
    case chip_vt_coffee_for_water_tmpr_k_entity:
    {
      vt_coffee_for_water_tmpr_deliver (request);

      break;
    }
    case chip_vt_coffee_for_coffee_k_entity:
    {
      vt_coffee_for_coffee_deliver (request);

      break;
    }
    case chip_vt_coffee_for_ticking_k_entity:
    {
      vt_coffee_for_ticking_deliver (request);

      break;
    }
    case chip_vt_coffee_tmr_k_entity:
    {
      vt_coffee_tmr_deliver (request);

      break;
    }
    case chip_vt_coffee_tmr1_k_entity:
    {
      vt_coffee_tmr1_deliver (request);

      break;
    }
    case chip_vt_coffee_tmr2_k_entity:
    {
      vt_coffee_tmr2_deliver (request);

      break;
    }
    case chip_vt_coffee_tmr3_k_entity:
    {
      vt_coffee_tmr3_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


