#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request);

void* vt_gui_out_msg_job (void);

void vt_gui_gui_polling_gui_deliver 
    (__po_hi_request_t* request);

void* vt_gui_gui_polling_gui_job (void);

void vt_coffee_get_init_tmpr_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_get_init_tmpr_job (void);

void vt_coffee_get_init_water_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_get_init_water_job (void);

void vt_coffee_for_water_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_for_water_job (void);

void vt_coffee_for_water_tmpr_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_for_water_tmpr_job (void);

void vt_coffee_for_coffee_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_for_coffee_job (void);

void vt_coffee_for_ticking_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_for_ticking_job (void);

void vt_coffee_tmr_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_tmr_job (void);

void vt_coffee_tmr1_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_tmr1_job (void);

void vt_coffee_tmr2_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_tmr2_job (void);

void vt_coffee_tmr3_deliver 
    (__po_hi_request_t* request);

void* vt_coffee_tmr3_job (void);

void vt_chip_timer_manager_tick_100ms_deliver 
    (__po_hi_request_t* request);

void* vt_chip_timer_manager_tick_100ms_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
