#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_taste_protected_object 
    (process_package__taste_protected_object value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (&(value), message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_unmarshall_type_taste_protected_object 
    (process_package__taste_protected_object* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_marshall_type_mystring_buffer_max_impl 
    (dataview__mystring_buffer_max_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (value, message, 264 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_unmarshall_type_mystring_buffer_max_impl 
    (dataview__mystring_buffer_max_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 264 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_marshall_type_stream_element_buffer 
    (dataview__stream_element_buffer value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_char (value, message, offset);
}

void __po_hi_unmarshall_type_stream_element_buffer 
    (dataview__stream_element_buffer* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_char (value, message, offset);
}

void __po_hi_marshall_type_unsigned_32 
    (base_types__unsigned_32 value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_uint32 (value, message, offset);
}

void __po_hi_unmarshall_type_unsigned_32 
    (base_types__unsigned_32* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_uint32 (value, message, offset);
}

void __po_hi_marshall_type_mystring_buffer_impl 
    (dataview__mystring_buffer_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_max_impl (value.buffer, message, offset);
  __po_hi_marshall_uint32 (value.length, message, offset);
}

void __po_hi_unmarshall_type_mystring_buffer_impl 
    (dataview__mystring_buffer_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_max_impl (&(value->buffer), message, offset);
  __po_hi_unmarshall_uint32 (&(value->length), message, offset);
}

void __po_hi_marshall_type_t_int32_buffer_max_impl 
    (dataview__t_int32_buffer_max_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (value, message, 8 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_unmarshall_type_t_int32_buffer_max_impl 
    (dataview__t_int32_buffer_max_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 8 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_marshall_type_t_int32_buffer_impl 
    (dataview__t_int32_buffer_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_max_impl (value.buffer, message, offset);
  __po_hi_marshall_uint32 (value.length, message, offset);
}

void __po_hi_unmarshall_type_t_int32_buffer_impl 
    (dataview__t_int32_buffer_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_max_impl (&(value->buffer), message, offset);
  __po_hi_unmarshall_uint32 (&(value->length), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_inport_artificial_out_msg 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_inport_artificial_out_msg 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_get_init_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_gui_out_msg_global_outport_get_init_tmpr_vt.vt_gui_out_msg_global_outport_get_init_tmpr_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_get_init_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_get_init_tmpr_vt.vt_gui_out_msg_global_outport_get_init_tmpr_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_get_init_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_gui_out_msg_global_outport_get_init_water_vt.vt_gui_out_msg_global_outport_get_init_water_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_get_init_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_get_init_water_vt.vt_gui_out_msg_global_outport_get_init_water_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_for_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_out_msg_global_outport_for_water_vt.vt_gui_out_msg_global_outport_for_water_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_for_water_vt.vt_gui_out_msg_global_outport_for_water_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_for_water_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_out_msg_global_outport_for_water_tmpr_vt.vt_gui_out_msg_global_outport_for_water_tmpr_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_water_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_for_water_tmpr_vt.vt_gui_out_msg_global_outport_for_water_tmpr_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_for_coffee_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_out_msg_global_outport_for_coffee_vt.vt_gui_out_msg_global_outport_for_coffee_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_coffee_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_for_coffee_vt.vt_gui_out_msg_global_outport_for_coffee_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_out_msg_outport_for_ticking_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_out_msg_global_outport_for_ticking_vt.vt_gui_out_msg_global_outport_for_ticking_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_ticking_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_out_msg_global_outport_for_ticking_vt.vt_gui_out_msg_global_outport_for_ticking_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt.vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt.vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_get_init_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_get_init_water_vt.vt_gui_gui_polling_gui_global_outport_get_init_water_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_get_init_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_get_init_water_vt.vt_gui_gui_polling_gui_global_outport_get_init_water_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_for_water_vt.vt_gui_gui_polling_gui_global_outport_for_water_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_water_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_for_water_vt.vt_gui_gui_polling_gui_global_outport_for_water_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt.vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt.vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_coffee_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_for_coffee_vt.vt_gui_gui_polling_gui_global_outport_for_coffee_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_coffee_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_for_coffee_vt.vt_gui_gui_polling_gui_global_outport_for_coffee_vt), message, offset);
}

void __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_ticking_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_gui_gui_polling_gui_global_outport_for_ticking_vt.vt_gui_gui_polling_gui_global_outport_for_ticking_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_ticking_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_gui_gui_polling_gui_global_outport_for_ticking_vt.vt_gui_gui_polling_gui_global_outport_for_ticking_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_get_init_tmpr_inport_artificial_get_init_tmpr 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_get_init_tmpr_inport_artificial_get_init_tmpr 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr.vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr), message, offset);
}

void __po_hi_marshall_request_vt_coffee_get_init_tmpr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_get_init_tmpr_global_outport_out_msg_vt.vt_coffee_get_init_tmpr_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_get_init_tmpr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_get_init_tmpr_global_outport_out_msg_vt.vt_coffee_get_init_tmpr_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_get_init_water_inport_artificial_get_init_water 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_t_int32_buffer_impl (request->vars.vt_coffee_get_init_water_global_inport_artificial_get_init_water.vt_coffee_get_init_water_global_inport_artificial_get_init_water, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_get_init_water_inport_artificial_get_init_water 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_t_int32_buffer_impl (&(request->vars.vt_coffee_get_init_water_global_inport_artificial_get_init_water.vt_coffee_get_init_water_global_inport_artificial_get_init_water), message, offset);
}

void __po_hi_marshall_request_vt_coffee_get_init_water_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_get_init_water_global_outport_out_msg_vt.vt_coffee_get_init_water_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_get_init_water_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_get_init_water_global_outport_out_msg_vt.vt_coffee_get_init_water_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_water_inport_artificial_for_water 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_water_global_inport_artificial_for_water.vt_coffee_for_water_global_inport_artificial_for_water, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_water_inport_artificial_for_water 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_water_global_inport_artificial_for_water.vt_coffee_for_water_global_inport_artificial_for_water), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_water_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_water_global_outport_out_msg_vt.vt_coffee_for_water_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_water_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_water_global_outport_out_msg_vt.vt_coffee_for_water_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_water_tmpr_inport_artificial_for_water_tmpr 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_water_tmpr_inport_artificial_for_water_tmpr 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr.vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_water_tmpr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_water_tmpr_global_outport_out_msg_vt.vt_coffee_for_water_tmpr_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_water_tmpr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_water_tmpr_global_outport_out_msg_vt.vt_coffee_for_water_tmpr_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_coffee_inport_artificial_for_coffee 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_coffee_global_inport_artificial_for_coffee.vt_coffee_for_coffee_global_inport_artificial_for_coffee, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_coffee_inport_artificial_for_coffee 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_coffee_global_inport_artificial_for_coffee.vt_coffee_for_coffee_global_inport_artificial_for_coffee), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_coffee_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_coffee_global_outport_out_msg_vt.vt_coffee_for_coffee_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_coffee_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_coffee_global_outport_out_msg_vt.vt_coffee_for_coffee_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_ticking_inport_artificial_for_ticking 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_ticking_global_inport_artificial_for_ticking.vt_coffee_for_ticking_global_inport_artificial_for_ticking, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_ticking_inport_artificial_for_ticking 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_ticking_global_inport_artificial_for_ticking.vt_coffee_for_ticking_global_inport_artificial_for_ticking), message, offset);
}

void __po_hi_marshall_request_vt_coffee_for_ticking_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_for_ticking_global_outport_out_msg_vt.vt_coffee_for_ticking_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_for_ticking_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_for_ticking_global_outport_out_msg_vt.vt_coffee_for_ticking_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_tmr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_tmr_global_outport_out_msg_vt.vt_coffee_tmr_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_tmr_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_tmr_global_outport_out_msg_vt.vt_coffee_tmr_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_tmr1_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_tmr1_global_outport_out_msg_vt.vt_coffee_tmr1_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_tmr1_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_tmr1_global_outport_out_msg_vt.vt_coffee_tmr1_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_tmr2_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_tmr2_global_outport_out_msg_vt.vt_coffee_tmr2_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_tmr2_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_tmr2_global_outport_out_msg_vt.vt_coffee_tmr2_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request_vt_coffee_tmr3_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_mystring_buffer_impl (request->vars.vt_coffee_tmr3_global_outport_out_msg_vt.vt_coffee_tmr3_global_outport_out_msg_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_coffee_tmr3_outport_out_msg_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_mystring_buffer_impl (&(request->vars.vt_coffee_tmr3_global_outport_out_msg_vt.vt_coffee_tmr3_global_outport_out_msg_vt), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_marshall_request_vt_gui_out_msg_inport_artificial_out_msg (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_get_init_tmpr_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_get_init_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_get_init_water_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_get_init_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_water_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_for_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_water_tmpr_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_for_water_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_coffee_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_for_coffee_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_ticking_vt:
    {
      __po_hi_marshall_request_vt_gui_out_msg_outport_for_ticking_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_get_init_water_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_get_init_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_water_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_coffee_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_coffee_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_ticking_vt:
    {
      __po_hi_marshall_request_vt_gui_gui_polling_gui_outport_for_ticking_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr:
    {
      __po_hi_marshall_request_vt_coffee_get_init_tmpr_inport_artificial_get_init_tmpr (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_tmpr_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_get_init_tmpr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_water_global_inport_artificial_get_init_water:
    {
      __po_hi_marshall_request_vt_coffee_get_init_water_inport_artificial_get_init_water (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_water_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_get_init_water_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_global_inport_artificial_for_water:
    {
      __po_hi_marshall_request_vt_coffee_for_water_inport_artificial_for_water (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_for_water_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr:
    {
      __po_hi_marshall_request_vt_coffee_for_water_tmpr_inport_artificial_for_water_tmpr (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_tmpr_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_for_water_tmpr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_coffee_global_inport_artificial_for_coffee:
    {
      __po_hi_marshall_request_vt_coffee_for_coffee_inport_artificial_for_coffee (request, message, &(offset));

      break;
    }
    case vt_coffee_for_coffee_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_for_coffee_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_ticking_global_inport_artificial_for_ticking:
    {
      __po_hi_marshall_request_vt_coffee_for_ticking_inport_artificial_for_ticking (request, message, &(offset));

      break;
    }
    case vt_coffee_for_ticking_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_for_ticking_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_tmr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr1_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_tmr1_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr2_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_tmr2_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr3_global_outport_out_msg_vt:
    {
      __po_hi_marshall_request_vt_coffee_tmr3_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_inport_artificial_out_msg (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_get_init_tmpr_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_get_init_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_get_init_water_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_get_init_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_water_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_water_tmpr_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_water_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_coffee_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_coffee_vt (request, message, &(offset));

      break;
    }
    case vt_gui_out_msg_global_outport_for_ticking_vt:
    {
      __po_hi_unmarshall_request_vt_gui_out_msg_outport_for_ticking_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_get_init_tmpr_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_get_init_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_get_init_water_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_get_init_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_water_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_water_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_water_tmpr_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_water_tmpr_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_coffee_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_coffee_vt (request, message, &(offset));

      break;
    }
    case vt_gui_gui_polling_gui_global_outport_for_ticking_vt:
    {
      __po_hi_unmarshall_request_vt_gui_gui_polling_gui_outport_for_ticking_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_tmpr_global_inport_artificial_get_init_tmpr:
    {
      __po_hi_unmarshall_request_vt_coffee_get_init_tmpr_inport_artificial_get_init_tmpr (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_tmpr_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_get_init_tmpr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_water_global_inport_artificial_get_init_water:
    {
      __po_hi_unmarshall_request_vt_coffee_get_init_water_inport_artificial_get_init_water (request, message, &(offset));

      break;
    }
    case vt_coffee_get_init_water_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_get_init_water_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_global_inport_artificial_for_water:
    {
      __po_hi_unmarshall_request_vt_coffee_for_water_inport_artificial_for_water (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_for_water_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_tmpr_global_inport_artificial_for_water_tmpr:
    {
      __po_hi_unmarshall_request_vt_coffee_for_water_tmpr_inport_artificial_for_water_tmpr (request, message, &(offset));

      break;
    }
    case vt_coffee_for_water_tmpr_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_for_water_tmpr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_coffee_global_inport_artificial_for_coffee:
    {
      __po_hi_unmarshall_request_vt_coffee_for_coffee_inport_artificial_for_coffee (request, message, &(offset));

      break;
    }
    case vt_coffee_for_coffee_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_for_coffee_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_for_ticking_global_inport_artificial_for_ticking:
    {
      __po_hi_unmarshall_request_vt_coffee_for_ticking_inport_artificial_for_ticking (request, message, &(offset));

      break;
    }
    case vt_coffee_for_ticking_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_for_ticking_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_tmr_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr1_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_tmr1_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr2_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_tmr2_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    case vt_coffee_tmr3_global_outport_out_msg_vt:
    {
      __po_hi_unmarshall_request_vt_coffee_tmr3_outport_out_msg_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


