-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
WITH TASTE_BasicTypes;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;


PACKAGE BODY TASTE_Dataview IS


SUBTYPE TASTE_Boolean_pattern_array_range is Natural range 1..1;
SUBTYPE TASTE_Boolean_pattern_array is adaasn1rtl.BitArray(TASTE_Boolean_pattern_array_range);
TASTE_Boolean_pattern:CONSTANT TASTE_Boolean_pattern_array := TASTE_Boolean_pattern_array'(
                                                                                           1=>1);

FUNCTION asn1SccTASTE_Boolean_Init return asn1SccTASTE_Boolean
IS 
BEGIN
    RETURN FALSE;
END asn1SccTASTE_Boolean_Init;

function asn1SccTASTE_Boolean_Equal(val1, val2: in asn1SccTASTE_Boolean) return Boolean
is
begin
    return val1 = val2;
end asn1SccTASTE_Boolean_Equal;

 

END TASTE_Dataview;