#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
extern process_package__taste_protected_object durationsys_protected;
extern process_package__taste_protected_object chip_timer_manager_protected;
__po_hi_port_t __po_hi_vt_gui_outputmsg_outport_inputmsg_vt_local_destinations[1] = {vt_durationsys_inputmsg_global_inport_artificial_inputmsg};
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_woffsets[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_offsets[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_used_size[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_empties[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_first[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_outputmsg_recent[__po_hi_vt_gui_outputmsg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_outputmsg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_outputmsg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_outputmsg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_n_dest[__po_hi_vt_gui_outputmsg_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_gui_outputmsg_fifo_size[__po_hi_vt_gui_outputmsg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_outputmsg_destinations[__po_hi_vt_gui_outputmsg_nb_ports] = {NULL,__po_hi_vt_gui_outputmsg_outport_inputmsg_vt_local_destinations};

/*!
 * \fn void vt_gui_outputmsg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_outputmsg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_outputmsg_deliver) stores the incoming request for the 
 * taskvt_gui_outputmsg
 */
void vt_gui_outputmsg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_outputmsg_global_inport_artificial_outputmsg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_outputmsg_k, vt_gui_outputmsg_local_inport_artificial_outputmsg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_outputmsg_job (void)
 * \brief Function executed by the task vt_gui_outputmsg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_outputmsg*/
extern void po_hi_c_vt_gui_outputmsg_artificial_outputmsg 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_outputmsg);
void* vt_gui_outputmsg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_outputmsg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_outputmsg_k, __po_hi_vt_gui_outputmsg_nb_ports, __po_hi_vt_gui_outputmsg_queue, __po_hi_vt_gui_outputmsg_fifo_size, __po_hi_vt_gui_outputmsg_first, __po_hi_vt_gui_outputmsg_offsets, __po_hi_vt_gui_outputmsg_woffsets, __po_hi_vt_gui_outputmsg_n_dest, __po_hi_vt_gui_outputmsg_destinations, __po_hi_vt_gui_outputmsg_used_size, __po_hi_vt_gui_outputmsg_history, __po_hi_vt_gui_outputmsg_recent, __po_hi_vt_gui_outputmsg_empties, __po_hi_vt_gui_outputmsg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_outputmsg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_outputmsg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_outputmsg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_outputmsg_local_inport_artificial_outputmsg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_outputmsg_k, vt_gui_outputmsg_local_inport_artificial_outputmsg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_outputmsg_k, vt_gui_outputmsg_local_inport_artificial_outputmsg, &(inport_artificial_outputmsg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_outputmsg_k, vt_gui_outputmsg_local_inport_artificial_outputmsg);

        }

        po_hi_c_vt_gui_outputmsg_artificial_outputmsg (chip_vt_gui_outputmsg_k, inport_artificial_outputmsg_request.vars.vt_gui_outputmsg_global_inport_artificial_outputmsg.vt_gui_outputmsg_global_inport_artificial_outputmsg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_outputmsg_k, vt_gui_outputmsg_global_outport_inputmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_outputmsg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_inputmsg_vt_local_destinations[1] = {vt_durationsys_inputmsg_global_inport_artificial_inputmsg};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_inputmsg_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_inputmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}

__po_hi_port_t __po_hi_vt_durationsys_inputmsg_outport_outputmsg_vt_local_destinations[1] = {vt_gui_outputmsg_global_inport_artificial_outputmsg};
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_woffsets[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_offsets[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_used_size[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_empties[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_first[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_request_t __po_hi_vt_durationsys_inputmsg_recent[__po_hi_vt_durationsys_inputmsg_nb_ports];
__po_hi_port_t __po_hi_vt_durationsys_inputmsg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_durationsys_inputmsg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_durationsys_inputmsg_history[1];
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_n_dest[__po_hi_vt_durationsys_inputmsg_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_durationsys_inputmsg_fifo_size[__po_hi_vt_durationsys_inputmsg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_durationsys_inputmsg_destinations[__po_hi_vt_durationsys_inputmsg_nb_ports] = {NULL,__po_hi_vt_durationsys_inputmsg_outport_outputmsg_vt_local_destinations};

/*!
 * \fn void vt_durationsys_inputmsg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_durationsys_inputmsg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_durationsys_inputmsg_deliver) stores the incoming request for the 
 * taskvt_durationsys_inputmsg
 */
void vt_durationsys_inputmsg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_durationsys_inputmsg_global_inport_artificial_inputmsg:
    {
      __po_hi_gqueue_store_in (chip_vt_durationsys_inputmsg_k, vt_durationsys_inputmsg_local_inport_artificial_inputmsg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_durationsys_inputmsg_job (void)
 * \brief Function executed by the task vt_durationsys_inputmsg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_durationsys_inputmsg*/
extern void po_hi_c_vt_durationsys_inputmsg_artificial_inputmsg 
    (__po_hi_task_id self,
    dataview__t_int32_buffer_impl inport_artificial_inputmsg);
void* vt_durationsys_inputmsg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_inputmsg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_durationsys_inputmsg_k, __po_hi_vt_durationsys_inputmsg_nb_ports, __po_hi_vt_durationsys_inputmsg_queue, __po_hi_vt_durationsys_inputmsg_fifo_size, __po_hi_vt_durationsys_inputmsg_first, __po_hi_vt_durationsys_inputmsg_offsets, __po_hi_vt_durationsys_inputmsg_woffsets, __po_hi_vt_durationsys_inputmsg_n_dest, __po_hi_vt_durationsys_inputmsg_destinations, __po_hi_vt_durationsys_inputmsg_used_size, __po_hi_vt_durationsys_inputmsg_history, __po_hi_vt_durationsys_inputmsg_recent, __po_hi_vt_durationsys_inputmsg_empties, __po_hi_vt_durationsys_inputmsg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_durationsys_inputmsg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_durationsys_inputmsg_k, &(port));
    __po_hi_compute_next_period (chip_vt_durationsys_inputmsg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_durationsys_inputmsg_local_inport_artificial_inputmsg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_durationsys_inputmsg_k, vt_durationsys_inputmsg_local_inport_artificial_inputmsg))
        {
                  __po_hi_gqueue_get_value (chip_vt_durationsys_inputmsg_k, vt_durationsys_inputmsg_local_inport_artificial_inputmsg, &(inport_artificial_inputmsg_request));
          __po_hi_gqueue_next_value (chip_vt_durationsys_inputmsg_k, vt_durationsys_inputmsg_local_inport_artificial_inputmsg);

        }

        po_hi_c_vt_durationsys_inputmsg_artificial_inputmsg (chip_vt_durationsys_inputmsg_k, inport_artificial_inputmsg_request.vars.vt_durationsys_inputmsg_global_inport_artificial_inputmsg.vt_durationsys_inputmsg_global_inport_artificial_inputmsg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_durationsys_inputmsg_k, vt_durationsys_inputmsg_global_outport_outputmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_durationsys_inputmsg_k);
  }
}

__po_hi_port_t __po_hi_vt_durationsys_sdltmr_outport_outputmsg_vt_local_destinations[1] = {vt_gui_outputmsg_global_inport_artificial_outputmsg};
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_woffsets[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_offsets[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_used_size[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_empties[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_first[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_request_t __po_hi_vt_durationsys_sdltmr_recent[__po_hi_vt_durationsys_sdltmr_nb_ports];
__po_hi_port_t __po_hi_vt_durationsys_sdltmr_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_durationsys_sdltmr_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_durationsys_sdltmr_history[1];
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_n_dest[__po_hi_vt_durationsys_sdltmr_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_durationsys_sdltmr_fifo_size[__po_hi_vt_durationsys_sdltmr_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_durationsys_sdltmr_destinations[__po_hi_vt_durationsys_sdltmr_nb_ports] = {NULL,__po_hi_vt_durationsys_sdltmr_outport_outputmsg_vt_local_destinations};

/*!
 * \fn void vt_durationsys_sdltmr_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_durationsys_sdltmr
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_durationsys_sdltmr_deliver) stores the incoming request for the 
 * taskvt_durationsys_sdltmr
 */
void vt_durationsys_sdltmr_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_durationsys_sdltmr_global_inport_artificial_sdltmr:
    {
      __po_hi_gqueue_store_in (chip_vt_durationsys_sdltmr_k, vt_durationsys_sdltmr_local_inport_artificial_sdltmr, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_durationsys_sdltmr_job (void)
 * \brief Function executed by the task vt_durationsys_sdltmr
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_durationsys_sdltmr*/
extern void po_hi_c_vt_durationsys_sdltmr_artificial_sdltmr 
    (__po_hi_task_id self);
void* vt_durationsys_sdltmr_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_durationsys_sdltmr_k, __po_hi_vt_durationsys_sdltmr_nb_ports, __po_hi_vt_durationsys_sdltmr_queue, __po_hi_vt_durationsys_sdltmr_fifo_size, __po_hi_vt_durationsys_sdltmr_first, __po_hi_vt_durationsys_sdltmr_offsets, __po_hi_vt_durationsys_sdltmr_woffsets, __po_hi_vt_durationsys_sdltmr_n_dest, __po_hi_vt_durationsys_sdltmr_destinations, __po_hi_vt_durationsys_sdltmr_used_size, __po_hi_vt_durationsys_sdltmr_history, __po_hi_vt_durationsys_sdltmr_recent, __po_hi_vt_durationsys_sdltmr_empties, __po_hi_vt_durationsys_sdltmr_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_durationsys_sdltmr_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_durationsys_sdltmr_k, &(port));
    __po_hi_compute_next_period (chip_vt_durationsys_sdltmr_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_durationsys_sdltmr_local_inport_artificial_sdltmr:
      {
        __po_hi_gqueue_next_value (chip_vt_durationsys_sdltmr_k, vt_durationsys_sdltmr_local_inport_artificial_sdltmr);

        po_hi_c_vt_durationsys_sdltmr_artificial_sdltmr (chip_vt_durationsys_sdltmr_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_durationsys_sdltmr_k, vt_durationsys_sdltmr_global_outport_outputmsg_vt);
    __po_hi_wait_for_next_period (chip_vt_durationsys_sdltmr_k);
  }
}

__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_outport_durationsys_sdltmr_vt_local_destinations[1] = {vt_durationsys_sdltmr_global_inport_artificial_sdltmr};
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_woffsets[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_offsets[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_used_size[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_empties[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_first[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_request_t __po_hi_vt_chip_timer_manager_tick_100ms_recent[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports];
__po_hi_port_t __po_hi_vt_chip_timer_manager_tick_100ms_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_chip_timer_manager_tick_100ms_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_chip_timer_manager_tick_100ms_history[0];
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_n_dest[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_chip_timer_manager_tick_100ms_fifo_size[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_chip_timer_manager_tick_100ms_destinations[__po_hi_vt_chip_timer_manager_tick_100ms_nb_ports] = {__po_hi_vt_chip_timer_manager_tick_100ms_outport_durationsys_sdltmr_vt_local_destinations};

/*!
 * \fn void* vt_chip_timer_manager_tick_100ms_job (void)
 * \brief Function executed by the task vt_chip_timer_manager_tick_100ms
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_chip_timer_manager_tick_100ms*/
extern void po_hi_c_vt_chip_timer_manager_tick_100ms_artificial_tick_100ms 
    (__po_hi_task_id self);
void* vt_chip_timer_manager_tick_100ms_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_chip_timer_manager_tick_100ms_k, __po_hi_vt_chip_timer_manager_tick_100ms_nb_ports, __po_hi_vt_chip_timer_manager_tick_100ms_queue, __po_hi_vt_chip_timer_manager_tick_100ms_fifo_size, __po_hi_vt_chip_timer_manager_tick_100ms_first, __po_hi_vt_chip_timer_manager_tick_100ms_offsets, __po_hi_vt_chip_timer_manager_tick_100ms_woffsets, __po_hi_vt_chip_timer_manager_tick_100ms_n_dest, __po_hi_vt_chip_timer_manager_tick_100ms_destinations, __po_hi_vt_chip_timer_manager_tick_100ms_used_size, __po_hi_vt_chip_timer_manager_tick_100ms_history, __po_hi_vt_chip_timer_manager_tick_100ms_recent, __po_hi_vt_chip_timer_manager_tick_100ms_empties, __po_hi_vt_chip_timer_manager_tick_100ms_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_chip_timer_manager_tick_100ms_artificial_tick_100ms (chip_vt_chip_timer_manager_tick_100ms_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_chip_timer_manager_tick_100ms_k, vt_chip_timer_manager_tick_100ms_global_outport_durationsys_sdltmr_vt);
    __po_hi_wait_for_next_period (chip_vt_chip_timer_manager_tick_100ms_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_vt_gui_outputmsg_k_entity:
    {
      vt_gui_outputmsg_deliver (request);

      break;
    }
    case chip_vt_durationsys_inputmsg_k_entity:
    {
      vt_durationsys_inputmsg_deliver (request);

      break;
    }
    case chip_vt_durationsys_sdltmr_k_entity:
    {
      vt_durationsys_sdltmr_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


