#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request);

void* vt_gui_out_msg_job (void);

void vt_gui_gui_polling_gui_deliver 
    (__po_hi_request_t* request);

void* vt_gui_gui_polling_gui_job (void);

void vt_compstate_switch_on_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_switch_on_job (void);

void vt_compstate_switch_off_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_switch_off_job (void);

void vt_compstate_restart_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_restart_job (void);

void vt_compstate_start_recording_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_start_recording_job (void);

void vt_compstate_pause_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_pause_job (void);

void vt_compstate_resume_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_resume_job (void);

void vt_compstate_stop_recording_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_stop_recording_job (void);

void vt_compstate_fail_deliver 
    (__po_hi_request_t* request);

void* vt_compstate_fail_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
