#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_inport_artificial_out_msg;

    } vt_gui_out_msg_global_inport_artificial_out_msg;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_switch_on_vt;

    } vt_gui_out_msg_global_outport_switch_on_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_switch_off_vt;

    } vt_gui_out_msg_global_outport_switch_off_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_restart_vt;

    } vt_gui_out_msg_global_outport_restart_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_start_recording_vt;

    } vt_gui_out_msg_global_outport_start_recording_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_pause_vt;

    } vt_gui_out_msg_global_outport_pause_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_resume_vt;

    } vt_gui_out_msg_global_outport_resume_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_fail_vt;

    } vt_gui_out_msg_global_outport_fail_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_out_msg_global_outport_stop_recording_vt;

    } vt_gui_out_msg_global_outport_stop_recording_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_switch_on_vt;

    } vt_gui_gui_polling_gui_global_outport_switch_on_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_switch_off_vt;

    } vt_gui_gui_polling_gui_global_outport_switch_off_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_restart_vt;

    } vt_gui_gui_polling_gui_global_outport_restart_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_start_recording_vt;

    } vt_gui_gui_polling_gui_global_outport_start_recording_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_pause_vt;

    } vt_gui_gui_polling_gui_global_outport_pause_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_resume_vt;

    } vt_gui_gui_polling_gui_global_outport_resume_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_fail_vt;

    } vt_gui_gui_polling_gui_global_outport_fail_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_gui_gui_polling_gui_global_outport_stop_recording_vt;

    } vt_gui_gui_polling_gui_global_outport_stop_recording_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_switch_on_global_inport_artificial_switch_on;

    } vt_compstate_switch_on_global_inport_artificial_switch_on;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_switch_on_global_outport_out_msg_vt;

    } vt_compstate_switch_on_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_switch_off_global_inport_artificial_switch_off;

    } vt_compstate_switch_off_global_inport_artificial_switch_off;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_switch_off_global_outport_out_msg_vt;

    } vt_compstate_switch_off_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_restart_global_inport_artificial_restart;

    } vt_compstate_restart_global_inport_artificial_restart;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_restart_global_outport_out_msg_vt;

    } vt_compstate_restart_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_start_recording_global_inport_artificial_start_recording;

    } vt_compstate_start_recording_global_inport_artificial_start_recording;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_start_recording_global_outport_out_msg_vt;

    } vt_compstate_start_recording_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_pause_global_inport_artificial_pause;

    } vt_compstate_pause_global_inport_artificial_pause;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_pause_global_outport_out_msg_vt;

    } vt_compstate_pause_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_resume_global_inport_artificial_resume;

    } vt_compstate_resume_global_inport_artificial_resume;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_resume_global_outport_out_msg_vt;

    } vt_compstate_resume_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_stop_recording_global_inport_artificial_stop_recording;

    } vt_compstate_stop_recording_global_inport_artificial_stop_recording;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_stop_recording_global_outport_out_msg_vt;

    } vt_compstate_stop_recording_global_outport_out_msg_vt;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_fail_global_inport_artificial_fail;

    } vt_compstate_fail_global_inport_artificial_fail;

    struct
    {
      dataview__mystring_buffer_impl vt_compstate_fail_global_outport_out_msg_vt;

    } vt_compstate_fail_global_outport_out_msg_vt;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
