#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object gui_protected;
extern process_package__taste_protected_object actions_protected;
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_push_vt_local_destinations[1] = {vt_actions_push_global_inport_artificial_push};
__po_hi_port_t __po_hi_vt_gui_out_msg_outport_tap_vt_local_destinations[1] = {vt_actions_tap_global_inport_artificial_tap};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_woffsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_offsets[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_used_size[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_empties[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_first[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_request_t __po_hi_vt_gui_out_msg_recent[__po_hi_vt_gui_out_msg_nb_ports];
__po_hi_port_t __po_hi_vt_gui_out_msg_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_out_msg_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_gui_out_msg_history[1];
__po_hi_port_id_t __po_hi_vt_gui_out_msg_n_dest[__po_hi_vt_gui_out_msg_nb_ports] = {0,1,1};
__po_hi_port_id_t __po_hi_vt_gui_out_msg_fifo_size[__po_hi_vt_gui_out_msg_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_out_msg_destinations[__po_hi_vt_gui_out_msg_nb_ports] = {NULL,__po_hi_vt_gui_out_msg_outport_push_vt_local_destinations,__po_hi_vt_gui_out_msg_outport_tap_vt_local_destinations};

/*!
 * \fn void vt_gui_out_msg_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_gui_out_msg
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_gui_out_msg_deliver) stores the incoming request for the 
 * taskvt_gui_out_msg
 */
void vt_gui_out_msg_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_gui_out_msg_global_inport_artificial_out_msg:
    {
      __po_hi_gqueue_store_in (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_gui_out_msg_job (void)
 * \brief Function executed by the task vt_gui_out_msg
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_gui_out_msg*/
extern void po_hi_c_vt_gui_out_msg_artificial_out_msg 
    (__po_hi_task_id self,
    dataview__t_int32_buffer_impl inport_artificial_out_msg);
void* vt_gui_out_msg_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_out_msg_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_out_msg_k, __po_hi_vt_gui_out_msg_nb_ports, __po_hi_vt_gui_out_msg_queue, __po_hi_vt_gui_out_msg_fifo_size, __po_hi_vt_gui_out_msg_first, __po_hi_vt_gui_out_msg_offsets, __po_hi_vt_gui_out_msg_woffsets, __po_hi_vt_gui_out_msg_n_dest, __po_hi_vt_gui_out_msg_destinations, __po_hi_vt_gui_out_msg_used_size, __po_hi_vt_gui_out_msg_history, __po_hi_vt_gui_out_msg_recent, __po_hi_vt_gui_out_msg_empties, __po_hi_vt_gui_out_msg_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_gui_out_msg_k, &(port));
    __po_hi_compute_next_period (chip_vt_gui_out_msg_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_gui_out_msg_local_inport_artificial_out_msg:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg))
        {
                  __po_hi_gqueue_get_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg, &(inport_artificial_out_msg_request));
          __po_hi_gqueue_next_value (chip_vt_gui_out_msg_k, vt_gui_out_msg_local_inport_artificial_out_msg);

        }

        po_hi_c_vt_gui_out_msg_artificial_out_msg (chip_vt_gui_out_msg_k, inport_artificial_out_msg_request.vars.vt_gui_out_msg_global_inport_artificial_out_msg.vt_gui_out_msg_global_inport_artificial_out_msg);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_push_vt);
    error =
     __po_hi_send_output (chip_vt_gui_out_msg_k, vt_gui_out_msg_global_outport_tap_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_out_msg_k);
  }
}

__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_push_vt_local_destinations[1] = {vt_actions_push_global_inport_artificial_push};
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_outport_tap_vt_local_destinations[1] = {vt_actions_tap_global_inport_artificial_tap};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_woffsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_offsets[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_used_size[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_empties[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_first[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_request_t __po_hi_vt_gui_gui_polling_gui_recent[__po_hi_vt_gui_gui_polling_gui_nb_ports];
__po_hi_port_t __po_hi_vt_gui_gui_polling_gui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_gui_gui_polling_gui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_gui_gui_polling_gui_history[0];
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_n_dest[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {1,1};
__po_hi_port_id_t __po_hi_vt_gui_gui_polling_gui_fifo_size[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_gui_gui_polling_gui_destinations[__po_hi_vt_gui_gui_polling_gui_nb_ports] = {__po_hi_vt_gui_gui_polling_gui_outport_push_vt_local_destinations,__po_hi_vt_gui_gui_polling_gui_outport_tap_vt_local_destinations};

/*!
 * \fn void* vt_gui_gui_polling_gui_job (void)
 * \brief Function executed by the task vt_gui_gui_polling_gui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_gui_gui_polling_gui*/
extern void po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui 
    (__po_hi_task_id self);
void* vt_gui_gui_polling_gui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_gui_gui_polling_gui_k, __po_hi_vt_gui_gui_polling_gui_nb_ports, __po_hi_vt_gui_gui_polling_gui_queue, __po_hi_vt_gui_gui_polling_gui_fifo_size, __po_hi_vt_gui_gui_polling_gui_first, __po_hi_vt_gui_gui_polling_gui_offsets, __po_hi_vt_gui_gui_polling_gui_woffsets, __po_hi_vt_gui_gui_polling_gui_n_dest, __po_hi_vt_gui_gui_polling_gui_destinations, __po_hi_vt_gui_gui_polling_gui_used_size, __po_hi_vt_gui_gui_polling_gui_history, __po_hi_vt_gui_gui_polling_gui_recent, __po_hi_vt_gui_gui_polling_gui_empties, __po_hi_vt_gui_gui_polling_gui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_gui_gui_polling_gui_artificial_gui_polling_gui (chip_vt_gui_gui_polling_gui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_push_vt);
    error =
     __po_hi_send_output (chip_vt_gui_gui_polling_gui_k, vt_gui_gui_polling_gui_global_outport_tap_vt);
    __po_hi_wait_for_next_period (chip_vt_gui_gui_polling_gui_k);
  }
}

__po_hi_port_t __po_hi_vt_actions_push_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_actions_push_woffsets[__po_hi_vt_actions_push_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_push_offsets[__po_hi_vt_actions_push_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_push_used_size[__po_hi_vt_actions_push_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_push_empties[__po_hi_vt_actions_push_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_push_first[__po_hi_vt_actions_push_nb_ports];
__po_hi_request_t __po_hi_vt_actions_push_recent[__po_hi_vt_actions_push_nb_ports];
__po_hi_port_t __po_hi_vt_actions_push_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_actions_push_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_actions_push_history[1];
__po_hi_port_id_t __po_hi_vt_actions_push_n_dest[__po_hi_vt_actions_push_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_actions_push_fifo_size[__po_hi_vt_actions_push_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_actions_push_destinations[__po_hi_vt_actions_push_nb_ports] = {NULL,__po_hi_vt_actions_push_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_actions_push_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_actions_push
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_actions_push_deliver) stores the incoming request for the 
 * taskvt_actions_push
 */
void vt_actions_push_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_actions_push_global_inport_artificial_push:
    {
      __po_hi_gqueue_store_in (chip_vt_actions_push_k, vt_actions_push_local_inport_artificial_push, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_actions_push_job (void)
 * \brief Function executed by the task vt_actions_push
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_actions_push*/
extern void po_hi_c_vt_actions_push_artificial_push 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_push);
void* vt_actions_push_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_push_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_actions_push_k, __po_hi_vt_actions_push_nb_ports, __po_hi_vt_actions_push_queue, __po_hi_vt_actions_push_fifo_size, __po_hi_vt_actions_push_first, __po_hi_vt_actions_push_offsets, __po_hi_vt_actions_push_woffsets, __po_hi_vt_actions_push_n_dest, __po_hi_vt_actions_push_destinations, __po_hi_vt_actions_push_used_size, __po_hi_vt_actions_push_history, __po_hi_vt_actions_push_recent, __po_hi_vt_actions_push_empties, __po_hi_vt_actions_push_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_actions_push_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_actions_push_k, &(port));
    __po_hi_compute_next_period (chip_vt_actions_push_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_actions_push_local_inport_artificial_push:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_actions_push_k, vt_actions_push_local_inport_artificial_push))
        {
                  __po_hi_gqueue_get_value (chip_vt_actions_push_k, vt_actions_push_local_inport_artificial_push, &(inport_artificial_push_request));
          __po_hi_gqueue_next_value (chip_vt_actions_push_k, vt_actions_push_local_inport_artificial_push);

        }

        po_hi_c_vt_actions_push_artificial_push (chip_vt_actions_push_k, inport_artificial_push_request.vars.vt_actions_push_global_inport_artificial_push.vt_actions_push_global_inport_artificial_push);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_actions_push_k, vt_actions_push_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_actions_push_k);
  }
}

__po_hi_port_t __po_hi_vt_actions_tap_outport_out_msg_vt_local_destinations[1] = {vt_gui_out_msg_global_inport_artificial_out_msg};
__po_hi_port_id_t __po_hi_vt_actions_tap_woffsets[__po_hi_vt_actions_tap_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_tap_offsets[__po_hi_vt_actions_tap_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_tap_used_size[__po_hi_vt_actions_tap_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_tap_empties[__po_hi_vt_actions_tap_nb_ports];
__po_hi_port_id_t __po_hi_vt_actions_tap_first[__po_hi_vt_actions_tap_nb_ports];
__po_hi_request_t __po_hi_vt_actions_tap_recent[__po_hi_vt_actions_tap_nb_ports];
__po_hi_port_t __po_hi_vt_actions_tap_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_actions_tap_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_actions_tap_history[1];
__po_hi_port_id_t __po_hi_vt_actions_tap_n_dest[__po_hi_vt_actions_tap_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_actions_tap_fifo_size[__po_hi_vt_actions_tap_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_actions_tap_destinations[__po_hi_vt_actions_tap_nb_ports] = {NULL,__po_hi_vt_actions_tap_outport_out_msg_vt_local_destinations};

/*!
 * \fn void vt_actions_tap_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_actions_tap
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_actions_tap_deliver) stores the incoming request for the 
 * taskvt_actions_tap
 */
void vt_actions_tap_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_actions_tap_global_inport_artificial_tap:
    {
      __po_hi_gqueue_store_in (chip_vt_actions_tap_k, vt_actions_tap_local_inport_artificial_tap, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_actions_tap_job (void)
 * \brief Function executed by the task vt_actions_tap
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_actions_tap*/
extern void po_hi_c_vt_actions_tap_artificial_tap 
    (__po_hi_task_id self,
    dataview__mystring_buffer_impl inport_artificial_tap);
void* vt_actions_tap_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_tap_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (chip_vt_actions_tap_k, __po_hi_vt_actions_tap_nb_ports, __po_hi_vt_actions_tap_queue, __po_hi_vt_actions_tap_fifo_size, __po_hi_vt_actions_tap_first, __po_hi_vt_actions_tap_offsets, __po_hi_vt_actions_tap_woffsets, __po_hi_vt_actions_tap_n_dest, __po_hi_vt_actions_tap_destinations, __po_hi_vt_actions_tap_used_size, __po_hi_vt_actions_tap_history, __po_hi_vt_actions_tap_recent, __po_hi_vt_actions_tap_empties, __po_hi_vt_actions_tap_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (chip_vt_actions_tap_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (chip_vt_actions_tap_k, &(port));
    __po_hi_compute_next_period (chip_vt_actions_tap_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_actions_tap_local_inport_artificial_tap:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (chip_vt_actions_tap_k, vt_actions_tap_local_inport_artificial_tap))
        {
                  __po_hi_gqueue_get_value (chip_vt_actions_tap_k, vt_actions_tap_local_inport_artificial_tap, &(inport_artificial_tap_request));
          __po_hi_gqueue_next_value (chip_vt_actions_tap_k, vt_actions_tap_local_inport_artificial_tap);

        }

        po_hi_c_vt_actions_tap_artificial_tap (chip_vt_actions_tap_k, inport_artificial_tap_request.vars.vt_actions_tap_global_inport_artificial_tap.vt_actions_tap_global_inport_artificial_tap);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (chip_vt_actions_tap_k, vt_actions_tap_global_outport_out_msg_vt);
    __po_hi_wait_for_next_period (chip_vt_actions_tap_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case chip_vt_gui_out_msg_k_entity:
    {
      vt_gui_out_msg_deliver (request);

      break;
    }
    case chip_vt_actions_push_k_entity:
    {
      vt_actions_push_deliver (request);

      break;
    }
    case chip_vt_actions_tap_k_entity:
    {
      vt_actions_tap_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


